#!/bin/sh
set -e

. $srcdir/common

# ATTENTION: this may overwrite a file (see fname below)
# todo: make this safe

FNAME="delme-cctest-346x63hg3"
test -e $FNAME && echo "Output file ($FNAME) exists. TODO: fix this test" && exit 1
trap 'rm $FNAME' EXIT

runtest '
var cc=ejs.ModuleLoader.get("cc");
cc.run("FILE *f; f=fopen(\"'$FNAME'\",\"w\"); fprintf(f,\"aaa\"); fclose(f); ","#include <stdio.h>");
cc.run("FILE *f; f=fopen(\"'$FNAME'\",\"w\"); fprintf(f,\"Hello World\"); fclose(f); ","#include <stdio.h>");
ejs.ModuleLoader.get("util").GC();
var File=ejs.ModuleLoader.get("File");
stream=File.read("'$FNAME'");
function assert(x){if (!x()) throw new Error(x.toSource());};
assert(function(){return (stream.readAll()=="Hello World");});
'
