#!/bin/sh
set -e

. $srcdir/common

# ATTENTION: this may overwrite a file (see fname below)
# todo: somehow make this safe and remove the file after the test

runtest '
ejs.ModuleLoader.load("File");
if (!File.mode.read)
	throw new Error("failed");
stream=File.open("Makefile",File.mode.read);
function assert(x){if (!x()) throw new Error(x.toSource());};
assert(function(){return stream instanceof Stream;});
if ((s=stream.read(10))!="# Makefile")
	throw new Error("failed: \""+s+"\"");
stream=File.read("Makefile");
if ((s=stream.read(10))!="# Makefile")
	throw new Error("failed: \""+s+"\"");
fname="delme-filetest-346x63hg3";
stream=File.write(fname);
stream.write("Hello World");
stream.sync();
stream=File.read(fname);
assert(function(){return stream.read(11)=="Hello World";});
'
rm delme-filetest-346x63hg3
