#!/bin/sh

set -e

. $srcdir/common

runtest '
function assert(x){if (!x()) throw new Error(x.toSource());};
var util=ejs.ModuleLoader.get("util");

function test() {
  var ltdl=ejs.ModuleLoader.get("ltdl");
  var fname=ejs.ModuleLoader.findFile(ejs.config.modules.libraryPath,"ejsltdl.la");
  var module=new ltdl.Ltmodule(fname);
  var func=module.getWrapper("ejsltdl_LTX_selfcheck",0,ltdl.defaultFlags);
  assert(function(){return func()==0;});
  assert(function(){return func(1)==1;});
  assert(function(){return func(1,2,3,100)==106;});
  var i,a=[];
  // note: the maximum number of arguments to a js function (in sm) is 65534
  var from=1,to=10;
  for (i=from;i<=to;++i)
    a[i]=i;
  assert(function(){return func.apply(this,a)==(from+to)*(to-from+1)/2;});
};

// this test requires us to load a module different from ourself
// since libtool does reference counting
function testGC() {
  var ltdl=ejs.ModuleLoader.get("ltdl");
  var fname=ejs.ModuleLoader.findFile(ejs.config.modules.libraryPath,"ejsexample.la");
  var module=new ltdl.Ltmodule(fname);
  return module.getWrapper("ejsexample_LTX_foo",0,ltdl.defaultFlags);
};

test();
util.GC();
assert(function(){
    // get wrapper function in a module
    var f=testGC();
    // try to GC module (it should not be collected!)
    util.GC();
    // test if wrapper function is still callable
    return f()=="foo";});
'
