#!/bin/sh
echo '
success=false;
ejs.ModuleLoader.load("Monitorable");
ejs.ModuleLoader.load("Stream");
function println(x){stdout.write(x+"\n");stdout.sync();}
function chopLine(x){
  return x.substring(x.indexOf("\n")+1,x.length);
}
function getStack(){
  return chopLine(chopLine(new Error().stack.toString()));
}
function debug(x){
//println(getStack());
}

debug("test");
t=new Monitorable();
t.monitor={
  onAdd:function(obj,prop,val){
    debug();
    success=true;
    return val;
  },
  onDelete:function(obj,prop){
    debug();
    success=true;
  },
  onGet:function(obj,prop,val){
    debug();
    success=true;
    return val;
  },
  onSet:function(obj,prop,val){
    debug();
    return val;
  }
};
t.a=10;
if ((!success)||(t.a!=10))
  throw new Error("failed");
success=false;
delete t.a;
if ((!success)||(t.a)) throw new Error("failed");
success=false;
var foo=t.a;
if (!success) throw new Error("failed");
'|../src/ejs
