#!/bin/sh
set -e

echo '
ejs.ModuleLoader.load("Stream");
ejs.ModuleLoader.load("Net");
'|../src/ejs

echo '
ejs.ModuleLoader.load("Net");
if (!Net._loadedScript) throw ("Script not loaded");
'|../src/ejs

echo '
ejs.ModuleLoader.load("Net");
try{
    stream=Net.connect("127.0.0.2",13);
    throw new Error("127.0.0.2 should not exist");
}catch(error){
}
'|../src/ejs

function runtest () {
    script="$1"
    echo $script|../src/ejs

    if which valgrind >/dev/null; then
	error=$(echo $script|valgrind -q --leak-check=yes --log-fd=1 ../src/ejs)
	if [ "x$error" != "x" ]; then
	    echo Memory leak: "$error"
	    exit 1
	fi
    else
	echo 'valgrind not found => skipping leak check'
    fi
}


runtest '
ejs.ModuleLoader.load("Net");
stream=Net.connect("localhost",13);
x=stream.read(100);
'
