#!/bin/sh
set -e

. $srcdir/common

echo '
ejs.ModuleLoader.load("Stream");
ejs.ModuleLoader.load("Net");
'|../src/ejs

echo '
ejs.ModuleLoader.load("Net");
if (!Net._loadedScript) throw ("Script not loaded");
'|../src/ejs

echo '
ejs.ModuleLoader.load("Net");
try{
    stream=Net.connect("127.0.0.2",13);
    throw new Error("127.0.0.2 should not exist");
}catch(error){
}
'|../src/ejs

runtest '
ejs.ModuleLoader.load("Net");
stream=Net.connect("localhost",13);
x=stream.read(100);
'
