#!/bin/bash
../src/ejs <<EOF
ejs.ModuleLoader.load("gl");
ejs.ModuleLoader.load("Stream");
function println(x){stdout.write(x+"\n");};
println("Vendor: "+gl.GetString(GL_VENDOR));
println("Renderer: "+gl.GetString(GL_RENDERER));
println("Version: "+gl.GetString(GL_VERSION));
println("Extensions: "+gl.GetString(GL_EXTENSIONS));

if (GL_NO_ERROR == undefined) throw new Error("failed");
if (gl.GetError() == undefined) throw new Error("failed");
if ( (error=gl.GetError()) != GL_NO_ERROR) {
    throw new Error("OpenGL error: "+error);
}
EOF
