#!/bin/sh
set -e

. $srcdir/common

runtest '
ejs.ModuleLoader.load("Net");
server=new Net.Server(10000);
cstream=Net.connect("localhost",10000);
server.handleNewConnection=function(id,stream){
    sstream=stream;
};
server.poll();
server.close();
try{
    Net.connect("localhost",10000);
    throw new Error("fail");
}catch(e){
}
delete server;
s="hello world!";
cstream.write(s);
cstream.sync();
if (sstream.read(s.length)!=s) throw new Error("fail");
try{
    Net.connect("localhost",10000);
    throw new Error("fail");
}catch(e){
}
'
