#!/bin/sh
set -e

function runtest () {
    script="$1"
    echo $script|../src/ejs

    if which valgrind >/dev/null; then
	error=$(echo $script|valgrind -q --leak-check=yes --log-fd=1 ../src/ejs)
	if [ "x$error" != "x" ]; then
	    echo Memory leak: "$error"
	    exit 1
	fi
    else
	echo 'valgrind not found => skipping leak check'
    fi
}

runtest '
ejs.ModuleLoader.load("Net");
server=new Net.Server(10000);
cstream=Net.connect("localhost",10000);
server.handleNewConnection=function(id,stream){
    sstream=stream;
};
server.poll();
server.close();
try{
    Net.connect("localhost",10000);
    throw new Error("fail");
}catch(e){
}
delete server;
s="hello world!";
cstream.write(s);
cstream.sync();
if (sstream.read(s.length)!=s) throw new Error("fail");
try{
    Net.connect("localhost",10000);
    throw new Error("fail");
}catch(e){
}
'
