#!/bin/bash
../src/ejs <<EOF
function assert(f) {
  if (!f()) throw Error("Assertion failed: "+f.toSource());
};

function expect(f,exp) {
  var res=f();
  if (res!=exp)
    throw Error("expect failed: "+f.toSource()+"="+uneval(res)+"!="+uneval(exp));
};

function isStream(stream)
{
  expect(function(){return typeof stream;},"object");
  expect(function(){return stream.__proto__;},x.Stream.prototype);
  expect(function(){return stream.constructor;},x.Stream);
  expect(function(){return stream.constructor.name;},"Stream");
  assert(function(){return stream instanceof x.Stream;});
}

x=ejs.ModuleLoader.get("Stream");
Stream=x.Stream;

expect(function(){return typeof x.Stream;},"function");
expect(function(){return x.Stream.name;},"Stream");

stream=new x.Stream();

isStream(stream);
isStream(x.stdin);
isStream(x.stdout);
isStream(x.stderr);
EOF

../src/ejs <<EOF
ejs.ModuleLoader.load("Stream");

s=new Stream.Stream();
success=true;
try{
	s.write("huhu");
	success=false;
}catch(e){}
try{
	x={};
	x.write=s.write;
	x.write("huhu");
	success=false;
}catch(e){
	// todo - better way to identify this exception
	if (e.message.indexOf("incompatible")<0)
		throw new Error("wrong exception");
}
try{
	x=s.write;
	x("huhu");
	success=false;
}catch(e){}
if (!success) throw new Error("failed");
if (!Stream.stdin) throw new Error("failed: Stream.stdin");
if (!Stream.stdout) throw new Error("failed: Stream.stdout");
if (!Stream.stderr) throw new Error("failed: Stream.stderr");
EOF

echo 'Hello World!'|../src/ejs <(echo '
ejs.ModuleLoader.load("Stream");
if ((s=Stream.stdin.read(11))!="Hello World") throw s;
')

O=$(echo '
ejs.ModuleLoader.load("Stream");
print=function(x){
    Stream.stdout.write(x);
}
println=function(x){print(x+"\n");}
println("Hello World");
'|../src/ejs)
E="Hello World"
if [ "x$O" != "x$E" ]; then
    echo failed: "$O != $E"
    exit 1
fi

O=$(echo '
ejs.ModuleLoader.load("Stream");
Stream.stderr.write("Hello World");
'|../src/ejs 2>&1)

if [ "x$O" != "xHello World" ]; then
    echo failed
fi

O=$(echo '
ejs.ModuleLoader.load("Stream");
x=100;
Stream.stdout.write(x);
'|../src/ejs)

if [ "x$O" != "x100" ]; then
    echo failed
fi
