#!/bin/bash
../src/ejs <<EOF

// not really needed for this test
ejs.ModuleLoader.load("Stream");
ejs.ModuleLoader.load("gl");
if (!gl.GetIntegerv(GL_STENCIL_BITS)[0])
	stderr.write("Warning no stencil buffer\n");
// end of not really needed for this test

ejs.ModuleLoader.load("svgl");
var svgdoc=new SVGDocument();
var rect=svgdoc.createElement("rect");

/*
var i;
for (i=0;i<400;++i) {
	gl.Clear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
	svgl.display(svgdoc);
	Video.swapBuffers();
}
*/
EOF
