#!/bin/bash
../src/ejs <<EOF

// not really needed for this test
var Stream=ejs.ModuleLoader.get("Stream");
var gl=ejs.ModuleLoader.get("gl");
// end of not really needed for this test

var Video=ejs.ModuleLoader.get("Video");
ejs.config.Input = ejs.config.Input || {};
ejs.config.Input.toggleFullscreen=function(){return Video.toggleFullscreen();};
var Input=ejs.ModuleLoader.get("Input");
if (!gl.GetIntegerv(GL_STENCIL_BITS)[0])
	Stream.stderr.write("Warning no stencil buffer\n");

var svgl=ejs.ModuleLoader.get("svgl");
var svgdoc=new svgl.SVGDocument();
// create svg element
var svg=svgdoc.createElement("svg");
svg.setAttribute("width",320);
svg.setAttribute("height",240);
// create rectangle
var rect=svgdoc.createElement("rect");
rect.setAttribute("width",100);
rect.setAttribute("height",100);
rect.setAttribute("x",160);
rect.setAttribute("y",140-10);
rect.setAttribute("style","fill:red;stroke:green;stroke-width:10");
// create text
var text=svgdoc.createElement("text");
text.appendChild(svgdoc.createTextNode("\u00C4tsch;-)"));
text.setAttribute("style","font-size:32;text-anchor:middle;fill:black");
text.setAttribute("x",160);
text.setAttribute("y",100);
text.childNodes.item(0).nodeValue="Hello";
svgdoc.appendChild(svg);
svg.appendChild(rect);
svg.appendChild(text);
svgl.selectDocument(svgdoc);
var i;
for (i=0;i<400;++i) {
	gl.Clear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
	svgl.display();
	Input.poll();
	Video.swapBuffers();
}
EOF
