#!/bin/bash
../src/ejs <<EOF

// not really needed for this test
ejs.ModuleLoader.load("Stream");
ejs.ModuleLoader.load("gl");
if (!gl.GetIntegerv(GL_STENCIL_BITS)[0])
	stderr.write("Warning no stencil buffer\n");
// end of not really needed for this test

ejs.ModuleLoader.load("svgl");
var svgdoc=new SVGDocument();
// create svg element
var svg=svgdoc.createElement("svg");
svg.setAttribute("width",450);
svg.setAttribute("height",450);
// create rectangle
var rect=svgdoc.createElement("rect");
rect.setAttribute("width",100);
rect.setAttribute("height",100);
rect.setAttribute("x",200);
rect.setAttribute("y",200);
rect.setAttribute("style","fill:red;stroke:green;stroke-width:10");
// create text
var text=svgdoc.createElement("text");
text.setAttribute("style","fill:black");
//text.setNodeValue("Hello World!");
svgdoc.appendChild(svg).appendChild(rect).appendChild(text);

var i;
for (i=0;i<400;++i) {
	gl.Clear(GL_COLOR_BUFFER_BIT|GL_STENCIL_BUFFER_BIT);
	svgl.display(svgdoc);
	Video.swapBuffers();
}
EOF
