#!/bin/sh
set -e

. $srcdir/common

# ATTENTION: this may overwrite a file (see fname below)
# todo: make this safe

FNAME="delme-tcctest-346x63hg3"
test -e $FNAME && echo "Output file ($FNAME) exists. TODO: fix this test" && exit 1

runtest '
var tcc=ejs.ModuleLoader.get("tcc");
tcc.run("FILE *f; f=fopen(\"'$FNAME'\",\"w\"); fprintf(f,\"Hello World\"); fclose(f); ");
// TODO: remove the next line and the test will fail due to a bug in the tcc module
ejs.ModuleLoader.get("util").GC();
tcc.run("FILE *f; f=fopen(\"'$FNAME'\",\"w\"); fprintf(f,\"Hello World\"); fclose(f); ");
ejs.ModuleLoader.get("util").GC();
var File=ejs.ModuleLoader.get("File");
stream=File.read("'$FNAME'");
function assert(x){if (!x()) throw new Error(x.toSource());};
assert(function(){return (stream.readAll()=="Hello World");});
'
rm $FNAME
