#!/bin/bash
set -e

if test ! -f $(pwd)/src/egachine.js; then
	echo "You must type ./clean in the top level directory"
	exit 1
fi

. common.sh

rm -vf $(find -name "*.o" -o -name "*.so" -o -name "*.lo" -o -name "*.a") 

PROGRAMS="egachine egaserver egares"
for a in $PROGRAMS; do rm -vf src/$a; done
for a in $PROGRAMS; do rm -vf src/$a.exe; done

cd $SPIDERMONKEY_SRCDIR
rm -rf *.OBJ fdlibm/*.OBJ
make -f Makefile.ref clean
