#!/bin/bash

# similar to make clean

set -e

if test ! -f $(pwd)/src/egachine.js; then
	echo "You must type ./clean in the top level directory"
	exit 1
fi

. common.sh

rm -vf $(find -name "*.o" -o -name "*.so" -o -name "*.lo" -o -name "*.a") 

for a in $PROGRAMS $LIBPROGRAMS; do rm -vf src/$a src/$a.exe src/$a.bin; done

cd $SPIDERMONKEY_SRCDIR
rm -rf *.OBJ fdlibm/*.OBJ
make -f Makefile.ref clean

cd $SDLMIXER_SRCDIR
if test -f Makefile; then
    make distclean
fi