#!/bin/bash

set -e


# setup environment for cross compilation
export CC=i586-mingw32msvc-gcc
export CXX=i586-mingw32msvc-g++
export GCJ=i586-mingw32msvc-gcj
export GCJH=i586-mingw32msvc-gcjh
export LD=i586-mingw32msvc-ld
export AR=i586-mingw32msvc-ar
export RANLIB=i586-mingw32msvc-ranlib 
export DLLTOOL=i586-mingw32msvc-dlltool
export DLLWRAP=i586-mingw32msvc-dllwrap
export AS=i586-mingw32msvc-as
export NM=i586-mingw32msvc-nm
export OBJDUMP=i586-mingw32msvc-objdump
export STRIP=i586-mingw32msvc-strip

export EGACHINE_CROSS=1
source ./common.sh

#settings very specific to my setup
export PATH="$HOME/bin:/usr/local/i586-mingw32msvc/bin:$PATH"
export EXE=".exe"
LDFLAGS="$LDFLAGS -L/usr/local/i586-mingw32msvc/lib"
CXXFLAGS="$CXXFLAGS -I/usr/local/i586-mingw32msvc/include"

if [ "x$DEBUG" = "x" ]; then
    SM_BUILDDIR="mingwcross_OPT.OBJ"
    BUILD_OPT="BUILD_OPT=1"
else
    SM_BUILDDIR="mingwcross_DBG.OBJ"
fi
LDFLAGS="$LDFLAGS -L$SPIDERMONKEY_SRCDIR/$SM_BUILDDIR"
SDLMIXERLIBS="-lSDL_mixer"
COMMONFLAGS="-c -I$TOPSRCDIR -I$SPIDERMONKEY_SRCDIR -I$SPIDERMONKEY_SRCDIR/$SM_BUILDDIR -I. -I$SRCDIR -I$SRCDIR/common -DXP_WIN $(sigc-config --cflags)"
CLIENTFLAGS="$(sdl-config --cflags)"
DESTDIR=${DESTDIR:=/tmp/egachine-$PACKAGE_MAJOR_VERSION.$PACKAGE_MINOR_VERSION.$PACKAGE_MICRO_VERSION}
JSLIB="-ljs32"

# build spidermonkey
cd $SPIDERMONKEY_SRCDIR

#make -f Makefile.ref clean
#rm -rf *.OBJ
make -f Makefile.ref SOVER=1.5 SOMAJOR=1 $BUILD_OPT


# build egachine
cd $SRCDIR
echo "make[0]: Entering directory \`$SRCDIR'"
rm -vf $(find -name "*.o" -o -name "*.so" -o -name "*.lo" -o -name "*.a") egachine$EXE egaserver$EXE

for a in $(find . -name "*.cpp"); do 
    echo Compile $a
    if (echo $a|grep client >/dev/null); then
	FLAGS="$COMMONFLAGS $CLIENTFLAGS $CXXFLAGS"
    else
	FLAGS="$COMMONFLAGS $CXXFLAGS"
    fi
    run "$CXX -o ${a%*.cpp}.o $FLAGS $a"
done
# link client
echo Link egachine
run "$CXX -o egachine$EXE $LDFLAGS $(find -name *.o|grep -v server|grep -v tools)  $JSLIB $SDLMIXERLIBS $(sdl-config --libs) $(sigc-config --libs) -lopengl32 -lglu32 -lwsock32 -lwinmm -lSDL_image -lz"
# link server
echo Link egaserver
run "$CXX -o egaserver$EXE $LDFLAGS $(find -name *.o|grep -v client|grep -v tools) $JSLIB $(sigc-config --libs) -lwsock32 -lwinmm -lz"

# link egares
echo Link egares
run "$CXX -o egares$EXE $LDFLAGS $(find -name *.o|grep -v client|grep -v server|grep -v network) -lwinmm $JSLIB -lz"

# install
mkdir $DESTDIR

TEXTFILES="COPYING README THANKS AUTHORS TODO ChangeLog DONE"
for a in $TEXTFILES; do
    cp $TOPSRCDIR/$a $DESTDIR/$a.txt
done

cp $SRCDIR/*.js $DESTDIR

mkdir $DESTDIR/etc
install $SRCDIR/etc/*.js $DESTDIR/etc

mkdir $DESTDIR/examples
mkdir $DESTDIR/examples/client
mkdir $DESTDIR/examples/client/opengl
mkdir $DESTDIR/examples/server
mkdir $DESTDIR/examples/misc

for a in $(find examples -name "*.js"); do
    install $a $DESTDIR/$a
done

# create bat files for examples
DIRBAK=$(pwd)
cd "$DESTDIR"
for a in $(find examples/server -name "*.js"); do
    n=$(basename "$a")
    b=${n%*.js}.bat
    echo Create $b
    echo "@ECHO OFF" > $DESTDIR/$b
    echo "egaserver $a" >> $DESTDIR/$b
done
for a in $(find examples/client -name "*.js"); do
    n=$(basename "$a")
    b=${n%*.js}.bat
    echo Create $b
    echo "@ECHO OFF" > $DESTDIR/$b
    echo "egachine $a" >> $DESTDIR/$b
done
cd "$DIRBAK"

cat >$DESTDIR/README-SDL.txt <<EOF
Please distribute this file with the SDL runtime environment:

The Simple DirectMedia Layer (SDL for short) is a cross-platfrom library
designed to make it easy to write multi-media software, such as games and
emulators.

The Simple DirectMedia Layer library source code is available from:
http://www.libsdl.org/

This library is distributed under the terms of the GNU LGPL license:
http://www.gnu.org/copyleft/lesser.html

NOTE:
The SDL version included in this package is a modified 1.2.7 version.
src/video/wincommon/SDL_wingl* are from 1.2.4
The library was cross-compiled with a mingw cross compiler
from linux to win.

The configure options:
./configure --host=i586-mingw32 --prefix=/usr/local/i586-mingw32msvc \
    --enable-video-opengl --disable-nasm --disable-dependency-tracking \
    --disable-diskaudio --disable-video-dummy --disable-cdrom
EOF

# convert text files
find $DESTDIR -name "*.js" -exec unix2dos \{\} \;
find $DESTDIR -name "*.bat" -exec unix2dos \{\} \;
find $DESTDIR -name "*.txt" -exec unix2dos \{\} \;

for a in $PROGRAMS; do
    cp $a$EXE $DESTDIR
    $STRIP $DESTDIR/$a$EXE
done

cp $SPIDERMONKEY_SRCDIR/$SM_BUILDDIR/js32.dll $DESTDIR
$STRIP $DESTDIR/js32.dll

# copy libs
cp /usr/local/i586-mingw32msvc/bin/SDL.dll $DESTDIR
cp /usr/local/i586-mingw32msvc/bin/SDL_mixer.dll $DESTDIR
cp /usr/local/i586-mingw32msvc/lib/libSDL_image.dll $DESTDIR
cp /usr/local/i586-mingw32msvc/lib/libjpeg.dll $DESTDIR
cp /usr/local/i586-mingw32msvc/lib/libz.dll $DESTDIR
cp /usr/local/i586-mingw32msvc/lib/libpng.dll $DESTDIR


# permissions
chmod -x $DESTDIR/*.dll
chmod +x $DESTDIR/*.bat
chmod +x $DESTDIR/*.exe
