.TH EGACHINE 1 
.SH NAME
EGachine \- a JavaScript game engine.
.SH SYNOPSIS
.PP
.B egachine
[
.I script
]
[
.I arguments
]
.SH DESCRIPTION
.\" Putting a newline after each sentence can generate better output.
EGachine is a JavaScript game engine focused on 2D multi-player (networked) games. The idea is to provide a tool for learning by writing computer games. EGachine is based upon a simple extensible JavaScript shell (EJS) and different  modules providing functionality required for programing games.
.SH AUTHOR
Jens Thiele
karme@berlios.de
.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR ejs (1).
