#!/bin/bash

# script which does what normally "make install" does
# NOTES:
# - you have to do ./make yourself (unlike make install)
# - crossmake does install the files itself

set -e

if test ! -f $(pwd)/src/egachine.js; then
	echo "You must type ./install in the top level directory"
	exit 1
fi

source ./common.sh

INSTDATA="install -m 644"
DDOCDIR="$DESTDIR/$DOCDIR/egachine"
install -dv $DDOCDIR

TEXTFILES="COPYING README THANKS AUTHORS TODO ChangeLog DONE"
for a in $TEXTFILES; do
    $INSTDATA $TOPSRCDIR/$a $DDOCDIR/$a
done


EDATADIR="$DESTDIR/$DATADIR/egachine"
install -dv $EDATADIR
$INSTDATA $SRCDIR/*.js $EDATADIR

ECONFDIR="$DESTDIR/$SYSCONFDIR/egachine"
install -dv $ECONFDIR
$INSTDATA $SRCDIR/etc/*.js $ECONFDIR

EXDIR="$DDOCDIR/examples"
install -dv $EXDIR/client/opengl
install -dv $EXDIR/server

cd $SRCDIR/examples
for a in $(find -name "*.js"); do
    if head -1 $a |grep -v DONTINSTALL >/dev/null; then
	$INSTDATA $a $EXDIR/$a;
    fi
done

EBINDIR="$DESTDIR/$BINDIR"
ELIBDIR="$DESTDIR/$LIBDIR/egachine"
install -dv $EBINDIR
install -dv $ELIBDIR

install -s $SPIDERMONKEY_SRCDIR/$SM_BUILDDIR/libsmjs.so $ELIBDIR
install -s $SPIDERMONKEY_SRCDIR/$SM_BUILDDIR/smjs $ELIBDIR/smjs.bin

cd $SRCDIR
for a in $PROGRAMS; do
    install -s "$a.bin" $ELIBDIR

    cat > $EBINDIR/$a <<-EOF
	#!/bin/sh
	LD_LIBRARY_PATH=$LIBDIR/egachine
	export LD_LIBRARY_PATH
	exec $LIBDIR/egachine/$a.bin \$*
	EOF
    chmod +x $EBINDIR/$a
done

for a in $LIBPROGRAMS; do
    install -s "$a.bin" $ELIBDIR

    cat > $ELIBDIR/$a <<-EOF
	#!/bin/sh
	LD_LIBRARY_PATH=$LIBDIR/egachine
	export LD_LIBRARY_PATH
	exec $LIBDIR/egachine/$a.bin \$*
	EOF
    chmod +x $ELIBDIR/$a
done
