#!/bin/bash
set -e

if test ! -f $(pwd)/src/egachine.js; then
	echo "You must type ./install in the top level directory"
	exit 1
fi

source ./common.sh

INSTDATA="install -m 644"
DDOCDIR="$DESTDIR/$DOCDIR/egachine"
install -dv $DDOCDIR

TEXTFILES="COPYING README THANKS AUTHORS TODO ChangeLog DONE"
for a in $TEXTFILES; do
    $INSTDATA $TOPSRCDIR/$a $DDOCDIR/$a
done


EDATADIR="$DESTDIR/$DATADIR/egachine"
install -dv $EDATADIR
$INSTDATA $SRCDIR/*.js $EDATADIR

ECONFDIR="$DESTDIR/$SYSCONFDIR/egachine"
install -dv $ECONFDIR
$INSTDATA $SRCDIR/etc/*.js $ECONFDIR

EXDIR="$DDOCDIR/examples"
install -dv $EXDIR/client/opengl
install -dv $EXDIR/server
install -dv $EXDIR/misc

cd $SRCDIR/examples
for a in $(find -name "*.js"); do
    if head -1 $a |grep -v DONTINSTALL >/dev/null; then
	$INSTDATA $a $EXDIR/$a;
    fi
done

EBINDIR="$DESTDIR/$BINDIR"
install -dv $EBINDIR
cd $SRCDIR
for a in $PROGRAMS; do
    install -s "$a" $EBINDIR
    install -s "$a" $EBINDIR
done