#!/bin/bash

# script i use to build a complete release

set -e

if [ "x$USER" != "xjens" ]; then
	echo this script is probably not what you want
	exit 1
fi

if test ! -f $(pwd)/src/egachine.js; then
	echo "You must type ./release in the top level directory"
	exit 1
fi

. common.sh

# create source tar ball
./dist

VERSIONSTR="$PACKAGE_MAJOR_VERSION.$PACKAGE_MINOR_VERSION.$PACKAGE_MICRO_VERSION"
EGANAME="egachine-$VERSIONSTR"
RELEASEDIR="/tmp/$EGANAME"
mkdir $RELEASEDIR
cp $EGANAME.tar.gz $RELEASEDIR
cd $RELEASEDIR

# first cross compile windows binaries
tar xzvf $EGANAME.tar.gz
cd $EGANAME
install -dv $RELEASEDIR/win
DESTDIR=$RELEASEDIR/win/$EGANAME ./crossmake
cd ..
rm -rfv "$EGANAME"
cd win
zip -r "egachine-win32-$VERSIONSTR.zip" "$EGANAME"
mv *.zip ..
cd $RELEASEDIR
rm -rf win

# build debian package
tar xzvf $EGANAME.tar.gz
cd $EGANAME
export CXXFLAGS="-I/usr/local/include/SDL -Wall -W -O2"
dpkg-buildpackage -rfakeroot
cd $RELEASEDIR
rm -rf "$EGANAME"
