#!/bin/bash
# try to find a readline wrapper
# todo: - don't depend on which
#       - remove bashisms
#       - take a look at other readline wrappers: rlfe cle
#         for rl in rlwrap rlfe cle; do
#       - sometimes rlwrap immediately exits (select returns error ERESTARTNOHAND)
#         (seems this is caused by using the <() construct ?)
#         perhaps not?
#         https://bugzilla.redhat.com/bugzilla/show_bug.cgi?id=161468
#         http://www-128.ibm.com/developerworks/linux/linux390/linux-2.6.5-s390-25-april2004.html

for rl in rlwrap; do
    which $rl >/dev/null && echo Using $rl && exec $rl -b ' (){}[],+-=&^%$#@\;|' -f <(cat <<EOF
ejs.ModuleLoader.get
ejs.ModuleLoader.load
ejs.exit
EOF
) ejs shell.js
done
ejs shell.js
