/* DO NOT EDIT THIS FILE - it is generated by jsgl_gen */
{"ClearIndex",ejs_glClearIndex,1,0,0},
{"ClearColor",ejs_glClearColor,4,0,0},
{"Clear",ejs_glClear,1,0,0},
{"IndexMask",ejs_glIndexMask,1,0,0},
{"ColorMask",ejs_glColorMask,4,0,0},
{"AlphaFunc",ejs_glAlphaFunc,2,0,0},
{"BlendFunc",ejs_glBlendFunc,2,0,0},
{"LogicOp",ejs_glLogicOp,1,0,0},
{"CullFace",ejs_glCullFace,1,0,0},
{"FrontFace",ejs_glFrontFace,1,0,0},
{"PointSize",ejs_glPointSize,1,0,0},
{"LineWidth",ejs_glLineWidth,1,0,0},
{"LineStipple",ejs_glLineStipple,2,0,0},
{"PolygonMode",ejs_glPolygonMode,2,0,0},
{"PolygonOffset",ejs_glPolygonOffset,2,0,0},
/* TODO: glPolygonStipple */
/* TODO: glGetPolygonStipple */
{"EdgeFlag",ejs_glEdgeFlag,1,0,0},
/* TODO: glEdgeFlagv */
{"Scissor",ejs_glScissor,4,0,0},
/* TODO: glClipPlane */
/* TODO: glGetClipPlane */
{"DrawBuffer",ejs_glDrawBuffer,1,0,0},
{"ReadBuffer",ejs_glReadBuffer,1,0,0},
{"Enable",ejs_glEnable,1,0,0},
{"Disable",ejs_glDisable,1,0,0},
{"IsEnabled",ejs_glIsEnabled,1,0,0},
{"EnableClientState",ejs_glEnableClientState,1,0,0},
{"DisableClientState",ejs_glDisableClientState,1,0,0},
/* TODO: glGetBooleanv */
/* TODO: glGetDoublev */
/* TODO: glGetFloatv */
/* TODO: glGetIntegerv */
{"PushAttrib",ejs_glPushAttrib,1,0,0},
{"PopAttrib",ejs_glPopAttrib,0,0,0},
{"PushClientAttrib",ejs_glPushClientAttrib,1,0,0},
{"PopClientAttrib",ejs_glPopClientAttrib,0,0,0},
{"RenderMode",ejs_glRenderMode,1,0,0},
{"GetError",ejs_glGetError,0,0,0},
{"GetString",ejs_glGetString,1,0,0},
{"Finish",ejs_glFinish,0,0,0},
{"Flush",ejs_glFlush,0,0,0},
{"Hint",ejs_glHint,2,0,0},
{"ClearDepth",ejs_glClearDepth,1,0,0},
{"DepthFunc",ejs_glDepthFunc,1,0,0},
{"DepthMask",ejs_glDepthMask,1,0,0},
{"DepthRange",ejs_glDepthRange,2,0,0},
{"ClearAccum",ejs_glClearAccum,4,0,0},
{"Accum",ejs_glAccum,2,0,0},
{"MatrixMode",ejs_glMatrixMode,1,0,0},
{"Ortho",ejs_glOrtho,6,0,0},
{"Frustum",ejs_glFrustum,6,0,0},
{"Viewport",ejs_glViewport,4,0,0},
{"PushMatrix",ejs_glPushMatrix,0,0,0},
{"PopMatrix",ejs_glPopMatrix,0,0,0},
{"LoadIdentity",ejs_glLoadIdentity,0,0,0},
{"LoadMatrixd",ejs_glLoadMatrixd,1,0,0},
{"LoadMatrixf",ejs_glLoadMatrixf,1,0,0},
{"MultMatrixd",ejs_glMultMatrixd,1,0,0},
{"MultMatrixf",ejs_glMultMatrixf,1,0,0},
{"Rotated",ejs_glRotated,4,0,0},
{"Rotatef",ejs_glRotatef,4,0,0},
{"Scaled",ejs_glScaled,3,0,0},
{"Scalef",ejs_glScalef,3,0,0},
{"Translated",ejs_glTranslated,3,0,0},
{"Translatef",ejs_glTranslatef,3,0,0},
{"IsList",ejs_glIsList,1,0,0},
{"DeleteLists",ejs_glDeleteLists,2,0,0},
{"GenLists",ejs_glGenLists,1,0,0},
{"NewList",ejs_glNewList,2,0,0},
{"EndList",ejs_glEndList,0,0,0},
{"CallList",ejs_glCallList,1,0,0},
/* TODO: glCallLists */
{"ListBase",ejs_glListBase,1,0,0},
{"Begin",ejs_glBegin,1,0,0},
{"End",ejs_glEnd,0,0,0},
{"Vertex2d",ejs_glVertex2d,2,0,0},
{"Vertex2f",ejs_glVertex2f,2,0,0},
{"Vertex2i",ejs_glVertex2i,2,0,0},
{"Vertex2s",ejs_glVertex2s,2,0,0},
{"Vertex3d",ejs_glVertex3d,3,0,0},
{"Vertex3f",ejs_glVertex3f,3,0,0},
{"Vertex3i",ejs_glVertex3i,3,0,0},
{"Vertex3s",ejs_glVertex3s,3,0,0},
{"Vertex4d",ejs_glVertex4d,4,0,0},
{"Vertex4f",ejs_glVertex4f,4,0,0},
{"Vertex4i",ejs_glVertex4i,4,0,0},
{"Vertex4s",ejs_glVertex4s,4,0,0},
{"Vertex2dv",ejs_glVertex2dv,1,0,0},
{"Vertex2fv",ejs_glVertex2fv,1,0,0},
{"Vertex2iv",ejs_glVertex2iv,1,0,0},
{"Vertex2sv",ejs_glVertex2sv,1,0,0},
{"Vertex3dv",ejs_glVertex3dv,1,0,0},
{"Vertex3fv",ejs_glVertex3fv,1,0,0},
{"Vertex3iv",ejs_glVertex3iv,1,0,0},
{"Vertex3sv",ejs_glVertex3sv,1,0,0},
{"Vertex4dv",ejs_glVertex4dv,1,0,0},
{"Vertex4fv",ejs_glVertex4fv,1,0,0},
{"Vertex4iv",ejs_glVertex4iv,1,0,0},
{"Vertex4sv",ejs_glVertex4sv,1,0,0},
{"Normal3b",ejs_glNormal3b,3,0,0},
{"Normal3d",ejs_glNormal3d,3,0,0},
{"Normal3f",ejs_glNormal3f,3,0,0},
{"Normal3i",ejs_glNormal3i,3,0,0},
{"Normal3s",ejs_glNormal3s,3,0,0},
{"Normal3bv",ejs_glNormal3bv,1,0,0},
{"Normal3dv",ejs_glNormal3dv,1,0,0},
{"Normal3fv",ejs_glNormal3fv,1,0,0},
{"Normal3iv",ejs_glNormal3iv,1,0,0},
{"Normal3sv",ejs_glNormal3sv,1,0,0},
{"Indexd",ejs_glIndexd,1,0,0},
{"Indexf",ejs_glIndexf,1,0,0},
{"Indexi",ejs_glIndexi,1,0,0},
{"Indexs",ejs_glIndexs,1,0,0},
{"Indexub",ejs_glIndexub,1,0,0},
/* TODO: glIndexdv */
/* TODO: glIndexfv */
/* TODO: glIndexiv */
/* TODO: glIndexsv */
/* TODO: glIndexubv */
{"Color3b",ejs_glColor3b,3,0,0},
{"Color3d",ejs_glColor3d,3,0,0},
{"Color3f",ejs_glColor3f,3,0,0},
{"Color3i",ejs_glColor3i,3,0,0},
{"Color3s",ejs_glColor3s,3,0,0},
{"Color3ub",ejs_glColor3ub,3,0,0},
{"Color3ui",ejs_glColor3ui,3,0,0},
{"Color3us",ejs_glColor3us,3,0,0},
{"Color4b",ejs_glColor4b,4,0,0},
{"Color4d",ejs_glColor4d,4,0,0},
{"Color4f",ejs_glColor4f,4,0,0},
{"Color4i",ejs_glColor4i,4,0,0},
{"Color4s",ejs_glColor4s,4,0,0},
{"Color4ub",ejs_glColor4ub,4,0,0},
{"Color4ui",ejs_glColor4ui,4,0,0},
{"Color4us",ejs_glColor4us,4,0,0},
{"Color3bv",ejs_glColor3bv,1,0,0},
{"Color3dv",ejs_glColor3dv,1,0,0},
{"Color3fv",ejs_glColor3fv,1,0,0},
{"Color3iv",ejs_glColor3iv,1,0,0},
{"Color3sv",ejs_glColor3sv,1,0,0},
{"Color3ubv",ejs_glColor3ubv,1,0,0},
{"Color3uiv",ejs_glColor3uiv,1,0,0},
{"Color3usv",ejs_glColor3usv,1,0,0},
{"Color4bv",ejs_glColor4bv,1,0,0},
{"Color4dv",ejs_glColor4dv,1,0,0},
{"Color4fv",ejs_glColor4fv,1,0,0},
{"Color4iv",ejs_glColor4iv,1,0,0},
{"Color4sv",ejs_glColor4sv,1,0,0},
{"Color4ubv",ejs_glColor4ubv,1,0,0},
{"Color4uiv",ejs_glColor4uiv,1,0,0},
{"Color4usv",ejs_glColor4usv,1,0,0},
{"TexCoord1d",ejs_glTexCoord1d,1,0,0},
{"TexCoord1f",ejs_glTexCoord1f,1,0,0},
{"TexCoord1i",ejs_glTexCoord1i,1,0,0},
{"TexCoord1s",ejs_glTexCoord1s,1,0,0},
{"TexCoord2d",ejs_glTexCoord2d,2,0,0},
{"TexCoord2f",ejs_glTexCoord2f,2,0,0},
{"TexCoord2i",ejs_glTexCoord2i,2,0,0},
{"TexCoord2s",ejs_glTexCoord2s,2,0,0},
{"TexCoord3d",ejs_glTexCoord3d,3,0,0},
{"TexCoord3f",ejs_glTexCoord3f,3,0,0},
{"TexCoord3i",ejs_glTexCoord3i,3,0,0},
{"TexCoord3s",ejs_glTexCoord3s,3,0,0},
{"TexCoord4d",ejs_glTexCoord4d,4,0,0},
{"TexCoord4f",ejs_glTexCoord4f,4,0,0},
{"TexCoord4i",ejs_glTexCoord4i,4,0,0},
{"TexCoord4s",ejs_glTexCoord4s,4,0,0},
{"TexCoord1dv",ejs_glTexCoord1dv,1,0,0},
{"TexCoord1fv",ejs_glTexCoord1fv,1,0,0},
{"TexCoord1iv",ejs_glTexCoord1iv,1,0,0},
{"TexCoord1sv",ejs_glTexCoord1sv,1,0,0},
{"TexCoord2dv",ejs_glTexCoord2dv,1,0,0},
{"TexCoord2fv",ejs_glTexCoord2fv,1,0,0},
{"TexCoord2iv",ejs_glTexCoord2iv,1,0,0},
{"TexCoord2sv",ejs_glTexCoord2sv,1,0,0},
{"TexCoord3dv",ejs_glTexCoord3dv,1,0,0},
{"TexCoord3fv",ejs_glTexCoord3fv,1,0,0},
{"TexCoord3iv",ejs_glTexCoord3iv,1,0,0},
{"TexCoord3sv",ejs_glTexCoord3sv,1,0,0},
{"TexCoord4dv",ejs_glTexCoord4dv,1,0,0},
{"TexCoord4fv",ejs_glTexCoord4fv,1,0,0},
{"TexCoord4iv",ejs_glTexCoord4iv,1,0,0},
{"TexCoord4sv",ejs_glTexCoord4sv,1,0,0},
{"RasterPos2d",ejs_glRasterPos2d,2,0,0},
{"RasterPos2f",ejs_glRasterPos2f,2,0,0},
{"RasterPos2i",ejs_glRasterPos2i,2,0,0},
{"RasterPos2s",ejs_glRasterPos2s,2,0,0},
{"RasterPos3d",ejs_glRasterPos3d,3,0,0},
{"RasterPos3f",ejs_glRasterPos3f,3,0,0},
{"RasterPos3i",ejs_glRasterPos3i,3,0,0},
{"RasterPos3s",ejs_glRasterPos3s,3,0,0},
{"RasterPos4d",ejs_glRasterPos4d,4,0,0},
{"RasterPos4f",ejs_glRasterPos4f,4,0,0},
{"RasterPos4i",ejs_glRasterPos4i,4,0,0},
{"RasterPos4s",ejs_glRasterPos4s,4,0,0},
{"RasterPos2dv",ejs_glRasterPos2dv,1,0,0},
{"RasterPos2fv",ejs_glRasterPos2fv,1,0,0},
{"RasterPos2iv",ejs_glRasterPos2iv,1,0,0},
{"RasterPos2sv",ejs_glRasterPos2sv,1,0,0},
{"RasterPos3dv",ejs_glRasterPos3dv,1,0,0},
{"RasterPos3fv",ejs_glRasterPos3fv,1,0,0},
{"RasterPos3iv",ejs_glRasterPos3iv,1,0,0},
{"RasterPos3sv",ejs_glRasterPos3sv,1,0,0},
{"RasterPos4dv",ejs_glRasterPos4dv,1,0,0},
{"RasterPos4fv",ejs_glRasterPos4fv,1,0,0},
{"RasterPos4iv",ejs_glRasterPos4iv,1,0,0},
{"RasterPos4sv",ejs_glRasterPos4sv,1,0,0},
{"Rectd",ejs_glRectd,4,0,0},
{"Rectf",ejs_glRectf,4,0,0},
{"Recti",ejs_glRecti,4,0,0},
{"Rects",ejs_glRects,4,0,0},
/* TODO: glRectdv */
/* TODO: glRectfv */
/* TODO: glRectiv */
/* TODO: glRectsv */
/* TODO: glVertexPointer */
/* TODO: glNormalPointer */
/* TODO: glColorPointer */
/* TODO: glIndexPointer */
/* TODO: glTexCoordPointer */
/* TODO: glEdgeFlagPointer */
/* TODO: glGetPointerv */
{"ArrayElement",ejs_glArrayElement,1,0,0},
{"DrawArrays",ejs_glDrawArrays,3,0,0},
/* TODO: glDrawElements */
/* TODO: glInterleavedArrays */
{"ShadeModel",ejs_glShadeModel,1,0,0},
{"Lightf",ejs_glLightf,3,0,0},
{"Lighti",ejs_glLighti,3,0,0},
/* TODO: glLightfv */
/* TODO: glLightiv */
/* TODO: glGetLightfv */
/* TODO: glGetLightiv */
{"LightModelf",ejs_glLightModelf,2,0,0},
{"LightModeli",ejs_glLightModeli,2,0,0},
/* TODO: glLightModelfv */
/* TODO: glLightModeliv */
{"Materialf",ejs_glMaterialf,3,0,0},
{"Materiali",ejs_glMateriali,3,0,0},
/* TODO: glMaterialfv */
/* TODO: glMaterialiv */
/* TODO: glGetMaterialfv */
/* TODO: glGetMaterialiv */
{"ColorMaterial",ejs_glColorMaterial,2,0,0},
{"PixelZoom",ejs_glPixelZoom,2,0,0},
{"PixelStoref",ejs_glPixelStoref,2,0,0},
{"PixelStorei",ejs_glPixelStorei,2,0,0},
{"PixelTransferf",ejs_glPixelTransferf,2,0,0},
{"PixelTransferi",ejs_glPixelTransferi,2,0,0},
/* TODO: glPixelMapfv */
/* TODO: glPixelMapuiv */
/* TODO: glPixelMapusv */
/* TODO: glGetPixelMapfv */
/* TODO: glGetPixelMapuiv */
/* TODO: glGetPixelMapusv */
/* TODO: glBitmap */
/* TODO: glReadPixels */
/* TODO: glDrawPixels */
{"CopyPixels",ejs_glCopyPixels,5,0,0},
{"StencilFunc",ejs_glStencilFunc,3,0,0},
{"StencilMask",ejs_glStencilMask,1,0,0},
{"StencilOp",ejs_glStencilOp,3,0,0},
{"ClearStencil",ejs_glClearStencil,1,0,0},
{"TexGend",ejs_glTexGend,3,0,0},
{"TexGenf",ejs_glTexGenf,3,0,0},
{"TexGeni",ejs_glTexGeni,3,0,0},
/* TODO: glTexGendv */
/* TODO: glTexGenfv */
/* TODO: glTexGeniv */
/* TODO: glGetTexGendv */
/* TODO: glGetTexGenfv */
/* TODO: glGetTexGeniv */
{"TexEnvf",ejs_glTexEnvf,3,0,0},
{"TexEnvi",ejs_glTexEnvi,3,0,0},
/* TODO: glTexEnvfv */
/* TODO: glTexEnviv */
/* TODO: glGetTexEnvfv */
/* TODO: glGetTexEnviv */
{"TexParameterf",ejs_glTexParameterf,3,0,0},
{"TexParameteri",ejs_glTexParameteri,3,0,0},
/* TODO: glTexParameterfv */
/* TODO: glTexParameteriv */
/* TODO: glGetTexParameterfv */
/* TODO: glGetTexParameteriv */
/* TODO: glGetTexLevelParameterfv */
/* TODO: glGetTexLevelParameteriv */
/* TODO: glTexImage1D */
/* TODO: glTexImage2D */
/* TODO: glGetTexImage */
#ifdef GL_VERSION_1_1
/* TODO: glGenTextures */
/* TODO: glDeleteTextures */
{"BindTexture",ejs_glBindTexture,2,0,0},
/* TODO: glPrioritizeTextures */
/* TODO: glAreTexturesResident */
{"IsTexture",ejs_glIsTexture,1,0,0},
/* TODO: glTexSubImage1D */
/* TODO: glTexSubImage2D */
{"CopyTexImage1D",ejs_glCopyTexImage1D,7,0,0},
{"CopyTexImage2D",ejs_glCopyTexImage2D,8,0,0},
{"CopyTexSubImage1D",ejs_glCopyTexSubImage1D,6,0,0},
{"CopyTexSubImage2D",ejs_glCopyTexSubImage2D,8,0,0},
/* TODO: glMap1d */
/* TODO: glMap1f */
/* TODO: glMap2d */
/* TODO: glMap2f */
/* TODO: glGetMapdv */
/* TODO: glGetMapfv */
/* TODO: glGetMapiv */
{"EvalCoord1d",ejs_glEvalCoord1d,1,0,0},
{"EvalCoord1f",ejs_glEvalCoord1f,1,0,0},
{"EvalCoord1dv",ejs_glEvalCoord1dv,1,0,0},
{"EvalCoord1fv",ejs_glEvalCoord1fv,1,0,0},
{"EvalCoord2d",ejs_glEvalCoord2d,2,0,0},
{"EvalCoord2f",ejs_glEvalCoord2f,2,0,0},
{"EvalCoord2dv",ejs_glEvalCoord2dv,1,0,0},
{"EvalCoord2fv",ejs_glEvalCoord2fv,1,0,0},
{"MapGrid1d",ejs_glMapGrid1d,3,0,0},
{"MapGrid1f",ejs_glMapGrid1f,3,0,0},
{"MapGrid2d",ejs_glMapGrid2d,6,0,0},
{"MapGrid2f",ejs_glMapGrid2f,6,0,0},
{"EvalPoint1",ejs_glEvalPoint1,1,0,0},
{"EvalPoint2",ejs_glEvalPoint2,2,0,0},
{"EvalMesh1",ejs_glEvalMesh1,3,0,0},
{"EvalMesh2",ejs_glEvalMesh2,5,0,0},
{"Fogf",ejs_glFogf,2,0,0},
{"Fogi",ejs_glFogi,2,0,0},
/* TODO: glFogfv */
/* TODO: glFogiv */
/* TODO: glFeedbackBuffer */
{"PassThrough",ejs_glPassThrough,1,0,0},
/* TODO: glSelectBuffer */
{"InitNames",ejs_glInitNames,0,0,0},
{"LoadName",ejs_glLoadName,1,0,0},
{"PushName",ejs_glPushName,1,0,0},
{"PopName",ejs_glPopName,0,0,0},
#endif
#ifdef GL_VERSION_1_2
/* TODO: glDrawRangeElements */
/* TODO: glTexImage3D */
/* TODO: glTexSubImage3D */
{"CopyTexSubImage3D",ejs_glCopyTexSubImage3D,9,0,0},
/* TODO: glColorTable */
/* TODO: glColorSubTable */
/* TODO: glColorTableParameteriv */
/* TODO: glColorTableParameterfv */
{"CopyColorSubTable",ejs_glCopyColorSubTable,5,0,0},
{"CopyColorTable",ejs_glCopyColorTable,5,0,0},
/* TODO: glGetColorTable */
/* TODO: glGetColorTableParameterfv */
/* TODO: glGetColorTableParameteriv */
{"BlendEquation",ejs_glBlendEquation,1,0,0},
{"BlendColor",ejs_glBlendColor,4,0,0},
{"Histogram",ejs_glHistogram,4,0,0},
{"ResetHistogram",ejs_glResetHistogram,1,0,0},
/* TODO: glGetHistogram */
/* TODO: glGetHistogramParameterfv */
/* TODO: glGetHistogramParameteriv */
{"Minmax",ejs_glMinmax,3,0,0},
{"ResetMinmax",ejs_glResetMinmax,1,0,0},
/* TODO: glGetMinmax */
/* TODO: glGetMinmaxParameterfv */
/* TODO: glGetMinmaxParameteriv */
/* TODO: glConvolutionFilter1D */
/* TODO: glConvolutionFilter2D */
{"ConvolutionParameterf",ejs_glConvolutionParameterf,3,0,0},
/* TODO: glConvolutionParameterfv */
{"ConvolutionParameteri",ejs_glConvolutionParameteri,3,0,0},
/* TODO: glConvolutionParameteriv */
{"CopyConvolutionFilter1D",ejs_glCopyConvolutionFilter1D,5,0,0},
{"CopyConvolutionFilter2D",ejs_glCopyConvolutionFilter2D,6,0,0},
/* TODO: glGetConvolutionFilter */
/* TODO: glGetConvolutionParameterfv */
/* TODO: glGetConvolutionParameteriv */
/* TODO: glSeparableFilter2D */
/* TODO: glGetSeparableFilter */
#endif
#ifdef GL_VERSION_1_3
{"ActiveTexture",ejs_glActiveTexture,1,0,0},
{"ClientActiveTexture",ejs_glClientActiveTexture,1,0,0},
/* TODO: glCompressedTexImage1D */
/* TODO: glCompressedTexImage2D */
/* TODO: glCompressedTexImage3D */
/* TODO: glCompressedTexSubImage1D */
/* TODO: glCompressedTexSubImage2D */
/* TODO: glCompressedTexSubImage3D */
/* TODO: glGetCompressedTexImage */
{"MultiTexCoord1d",ejs_glMultiTexCoord1d,2,0,0},
{"MultiTexCoord1dv",ejs_glMultiTexCoord1dv,2,0,0},
{"MultiTexCoord1f",ejs_glMultiTexCoord1f,2,0,0},
{"MultiTexCoord1fv",ejs_glMultiTexCoord1fv,2,0,0},
{"MultiTexCoord1i",ejs_glMultiTexCoord1i,2,0,0},
{"MultiTexCoord1iv",ejs_glMultiTexCoord1iv,2,0,0},
{"MultiTexCoord1s",ejs_glMultiTexCoord1s,2,0,0},
{"MultiTexCoord1sv",ejs_glMultiTexCoord1sv,2,0,0},
{"MultiTexCoord2d",ejs_glMultiTexCoord2d,3,0,0},
{"MultiTexCoord2dv",ejs_glMultiTexCoord2dv,2,0,0},
{"MultiTexCoord2f",ejs_glMultiTexCoord2f,3,0,0},
{"MultiTexCoord2fv",ejs_glMultiTexCoord2fv,2,0,0},
{"MultiTexCoord2i",ejs_glMultiTexCoord2i,3,0,0},
{"MultiTexCoord2iv",ejs_glMultiTexCoord2iv,2,0,0},
{"MultiTexCoord2s",ejs_glMultiTexCoord2s,3,0,0},
{"MultiTexCoord2sv",ejs_glMultiTexCoord2sv,2,0,0},
{"MultiTexCoord3d",ejs_glMultiTexCoord3d,4,0,0},
{"MultiTexCoord3dv",ejs_glMultiTexCoord3dv,2,0,0},
{"MultiTexCoord3f",ejs_glMultiTexCoord3f,4,0,0},
{"MultiTexCoord3fv",ejs_glMultiTexCoord3fv,2,0,0},
{"MultiTexCoord3i",ejs_glMultiTexCoord3i,4,0,0},
{"MultiTexCoord3iv",ejs_glMultiTexCoord3iv,2,0,0},
{"MultiTexCoord3s",ejs_glMultiTexCoord3s,4,0,0},
{"MultiTexCoord3sv",ejs_glMultiTexCoord3sv,2,0,0},
{"MultiTexCoord4d",ejs_glMultiTexCoord4d,5,0,0},
{"MultiTexCoord4dv",ejs_glMultiTexCoord4dv,2,0,0},
{"MultiTexCoord4f",ejs_glMultiTexCoord4f,5,0,0},
{"MultiTexCoord4fv",ejs_glMultiTexCoord4fv,2,0,0},
{"MultiTexCoord4i",ejs_glMultiTexCoord4i,5,0,0},
{"MultiTexCoord4iv",ejs_glMultiTexCoord4iv,2,0,0},
{"MultiTexCoord4s",ejs_glMultiTexCoord4s,5,0,0},
{"MultiTexCoord4sv",ejs_glMultiTexCoord4sv,2,0,0},
{"LoadTransposeMatrixd",ejs_glLoadTransposeMatrixd,1,0,0},
{"LoadTransposeMatrixf",ejs_glLoadTransposeMatrixf,1,0,0},
{"MultTransposeMatrixd",ejs_glMultTransposeMatrixd,1,0,0},
{"MultTransposeMatrixf",ejs_glMultTransposeMatrixf,1,0,0},
{"SampleCoverage",ejs_glSampleCoverage,2,0,0},
#endif
