/* DO NOT EDIT THIS FILE - it is generated by jsgl_gen */
/* TODO: gluBeginCurve */
/* TODO: gluBeginPolygon */
/* TODO: gluBeginSurface */
/* TODO: gluBeginTrim */
/* TODO: gluBuild1DMipmapLevels */
/* TODO: gluBuild1DMipmaps */
/* TODO: gluBuild2DMipmapLevels */
/* TODO: gluBuild2DMipmaps */
/* TODO: gluBuild3DMipmapLevels */
/* TODO: gluBuild3DMipmaps */
/* TODO: gluCheckExtension */
/* TODO: gluCylinder */
/* TODO: gluDeleteNurbsRenderer */
/* TODO: gluDeleteQuadric */
/* TODO: gluDeleteTess */
/* TODO: gluDisk */
/* TODO: gluEndCurve */
/* TODO: gluEndPolygon */
/* TODO: gluEndSurface */
/* TODO: gluEndTrim */
{"ErrorString",ejs_gluErrorString,1,0,0},
/* TODO: gluGetNurbsProperty */
{"GetString",ejs_gluGetString,1,0,0},
/* TODO: gluGetTessProperty */
/* TODO: gluLoadSamplingMatrices */
{"LookAt",ejs_gluLookAt,9,0,0},
/* TODO: gluNextContour */
/* TODO: gluNurbsCallback */
/* TODO: gluNurbsCallbackData */
/* TODO: gluNurbsCallbackDataEXT */
/* TODO: gluNurbsCurve */
/* TODO: gluNurbsProperty */
/* TODO: gluNurbsSurface */
{"Ortho2D",ejs_gluOrtho2D,4,0,0},
/* TODO: gluPartialDisk */
{"Perspective",ejs_gluPerspective,4,0,0},
/* TODO: gluPickMatrix */
/* TODO: gluProject */
/* TODO: gluPwlCurve */
/* TODO: gluQuadricCallback */
/* TODO: gluQuadricDrawStyle */
/* TODO: gluQuadricNormals */
/* TODO: gluQuadricOrientation */
/* TODO: gluQuadricTexture */
/* TODO: gluScaleImage */
/* TODO: gluSphere */
/* TODO: gluTessBeginContour */
/* TODO: gluTessBeginPolygon */
/* TODO: gluTessCallback */
/* TODO: gluTessEndContour */
/* TODO: gluTessEndPolygon */
/* TODO: gluTessNormal */
/* TODO: gluTessProperty */
/* TODO: gluTessVertex */
/* TODO: gluUnProject */
/* TODO: gluUnProject4 */
