/* this file is autogenerated by gen_glgetnumargs - do not EDIT ! */
static int
jsgl_glGetNumArgs (GLenum e)
{
  switch (e)
    {
#ifdef GL_ACCUM_BLUE_BITS
    case GL_ACCUM_BLUE_BITS:
#endif
#ifdef GL_ACCUM_GREEN_BITS
    case GL_ACCUM_GREEN_BITS:
#endif
#ifdef GL_ACCUM_RED_BITS
    case GL_ACCUM_RED_BITS:
#endif
#ifdef GL_ACTIVE_TEXTURE_ARB
    case GL_ACTIVE_TEXTURE_ARB:
#endif
#ifdef GL_ALPHA_BIAS
    case GL_ALPHA_BIAS:
#endif
#ifdef GL_ALPHA_BITS
    case GL_ALPHA_BITS:
#endif
#ifdef GL_ALPHA_SCALE
    case GL_ALPHA_SCALE:
#endif
#ifdef GL_ALPHA_TEST
    case GL_ALPHA_TEST:
#endif
#ifdef GL_ALPHA_TEST_FUNC
    case GL_ALPHA_TEST_FUNC:
#endif
#ifdef GL_ALPHA_TEST_REF
    case GL_ALPHA_TEST_REF:
#endif
#ifdef GL_ATTRIB_STACK_DEPTH
    case GL_ATTRIB_STACK_DEPTH:
#endif
#ifdef GL_AUTO_NORMAL
    case GL_AUTO_NORMAL:
#endif
#ifdef GL_AUX_BUFFERS
    case GL_AUX_BUFFERS:
#endif
#ifdef GL_BLEND
    case GL_BLEND:
#endif
#ifdef GL_BLEND_DST
    case GL_BLEND_DST:
#endif
#ifdef GL_BLEND_EQUATION
    case GL_BLEND_EQUATION:
#endif
#ifdef GL_BLEND_SRC
    case GL_BLEND_SRC:
#endif
#ifdef GL_BLUE_BIAS
    case GL_BLUE_BIAS:
#endif
#ifdef GL_BLUE_BITS
    case GL_BLUE_BITS:
#endif
#ifdef GL_BLUE_SCALE
    case GL_BLUE_SCALE:
#endif
#ifdef GL_CLIENT_ACTIVE_TEXTURE_ARB
    case GL_CLIENT_ACTIVE_TEXTURE_ARB:
#endif
#ifdef GL_CLIENT_ATTRIB_STACK_DEPTH
    case GL_CLIENT_ATTRIB_STACK_DEPTH:
#endif
#ifdef GL_CLIP_PLANE0
    case GL_CLIP_PLANE0:
#endif
#ifdef GL_CLIP_PLANE1
    case GL_CLIP_PLANE1:
#endif
#ifdef GL_CLIP_PLANE2
    case GL_CLIP_PLANE2:
#endif
#ifdef GL_CLIP_PLANE3
    case GL_CLIP_PLANE3:
#endif
#ifdef GL_CLIP_PLANE4
    case GL_CLIP_PLANE4:
#endif
#ifdef GL_CLIP_PLANE5
    case GL_CLIP_PLANE5:
#endif
#ifdef GL_COLOR_ARRAY
    case GL_COLOR_ARRAY:
#endif
#ifdef GL_COLOR_ARRAY_SIZE
    case GL_COLOR_ARRAY_SIZE:
#endif
#ifdef GL_COLOR_ARRAY_STRIDE
    case GL_COLOR_ARRAY_STRIDE:
#endif
#ifdef GL_COLOR_ARRAY_TYPE
    case GL_COLOR_ARRAY_TYPE:
#endif
#ifdef GL_COLOR_LOGIC_OP
    case GL_COLOR_LOGIC_OP:
#endif
#ifdef GL_COLOR_MATERIAL
    case GL_COLOR_MATERIAL:
#endif
#ifdef GL_COLOR_MATERIAL_FACE
    case GL_COLOR_MATERIAL_FACE:
#endif
#ifdef GL_COLOR_MATERIAL_PARAMETER
    case GL_COLOR_MATERIAL_PARAMETER:
#endif
#ifdef GL_COLOR_MATRIX_STACK_DEPTH
    case GL_COLOR_MATRIX_STACK_DEPTH:
#endif
#ifdef GL_COLOR_TABLE
    case GL_COLOR_TABLE:
#endif
#ifdef GL_CONVOLUTION_1D
    case GL_CONVOLUTION_1D:
#endif
#ifdef GL_CONVOLUTION_2D
    case GL_CONVOLUTION_2D:
#endif
#ifdef GL_CULL_FACE
    case GL_CULL_FACE:
#endif
#ifdef GL_CULL_FACE_MODE
    case GL_CULL_FACE_MODE:
#endif
#ifdef GL_CURRENT_INDEX
    case GL_CURRENT_INDEX:
#endif
#ifdef GL_CURRENT_RASTER_DISTANCE
    case GL_CURRENT_RASTER_DISTANCE:
#endif
#ifdef GL_CURRENT_RASTER_INDEX
    case GL_CURRENT_RASTER_INDEX:
#endif
#ifdef GL_CURRENT_RASTER_POSITION_VALID
    case GL_CURRENT_RASTER_POSITION_VALID:
#endif
#ifdef GL_DEPTH_BIAS
    case GL_DEPTH_BIAS:
#endif
#ifdef GL_DEPTH_BITS
    case GL_DEPTH_BITS:
#endif
#ifdef GL_DEPTH_CLEAR_VALUE
    case GL_DEPTH_CLEAR_VALUE:
#endif
#ifdef GL_DEPTH_FUNC
    case GL_DEPTH_FUNC:
#endif
#ifdef GL_DEPTH_SCALE
    case GL_DEPTH_SCALE:
#endif
#ifdef GL_DEPTH_TEST
    case GL_DEPTH_TEST:
#endif
#ifdef GL_DEPTH_WRITEMASK
    case GL_DEPTH_WRITEMASK:
#endif
#ifdef GL_DITHER
    case GL_DITHER:
#endif
#ifdef GL_DOUBLEBUFFER
    case GL_DOUBLEBUFFER:
#endif
#ifdef GL_DRAW_BUFFER
    case GL_DRAW_BUFFER:
#endif
#ifdef GL_EDGE_FLAG
    case GL_EDGE_FLAG:
#endif
#ifdef GL_EDGE_FLAG_ARRAY
    case GL_EDGE_FLAG_ARRAY:
#endif
#ifdef GL_EDGE_FLAG_ARRAY_STRIDE
    case GL_EDGE_FLAG_ARRAY_STRIDE:
#endif
#ifdef GL_FEEDBACK_BUFFER_SIZE
    case GL_FEEDBACK_BUFFER_SIZE:
#endif
#ifdef GL_FEEDBACK_BUFFER_TYPE
    case GL_FEEDBACK_BUFFER_TYPE:
#endif
#ifdef GL_FOG
    case GL_FOG:
#endif
#ifdef GL_FOG_DENSITY
    case GL_FOG_DENSITY:
#endif
#ifdef GL_FOG_END
    case GL_FOG_END:
#endif
#ifdef GL_FOG_HINT
    case GL_FOG_HINT:
#endif
#ifdef GL_FOG_INDEX
    case GL_FOG_INDEX:
#endif
#ifdef GL_FOG_MODE
    case GL_FOG_MODE:
#endif
#ifdef GL_FOG_START
    case GL_FOG_START:
#endif
#ifdef GL_FRONT_FACE
    case GL_FRONT_FACE:
#endif
#ifdef GL_GREEN_BIAS
    case GL_GREEN_BIAS:
#endif
#ifdef GL_GREEN_BITS
    case GL_GREEN_BITS:
#endif
#ifdef GL_GREEN_SCALE
    case GL_GREEN_SCALE:
#endif
#ifdef GL_HISTOGRAM
    case GL_HISTOGRAM:
#endif
#ifdef GL_INDEX_ARRAY
    case GL_INDEX_ARRAY:
#endif
#ifdef GL_INDEX_ARRAY_STRIDE
    case GL_INDEX_ARRAY_STRIDE:
#endif
#ifdef GL_INDEX_ARRAY_TYPE
    case GL_INDEX_ARRAY_TYPE:
#endif
#ifdef GL_INDEX_BITS
    case GL_INDEX_BITS:
#endif
#ifdef GL_INDEX_CLEAR_VALUE
    case GL_INDEX_CLEAR_VALUE:
#endif
#ifdef GL_INDEX_LOGIC_OP
    case GL_INDEX_LOGIC_OP:
#endif
#ifdef GL_INDEX_MODE
    case GL_INDEX_MODE:
#endif
#ifdef GL_INDEX_OFFSET
    case GL_INDEX_OFFSET:
#endif
#ifdef GL_INDEX_SHIFT
    case GL_INDEX_SHIFT:
#endif
#ifdef GL_INDEX_WRITEMASK
    case GL_INDEX_WRITEMASK:
#endif
#ifdef GL_LIGHT0
    case GL_LIGHT0:
#endif
#ifdef GL_LIGHT1
    case GL_LIGHT1:
#endif
#ifdef GL_LIGHT2
    case GL_LIGHT2:
#endif
#ifdef GL_LIGHT3
    case GL_LIGHT3:
#endif
#ifdef GL_LIGHT4
    case GL_LIGHT4:
#endif
#ifdef GL_LIGHT5
    case GL_LIGHT5:
#endif
#ifdef GL_LIGHT6
    case GL_LIGHT6:
#endif
#ifdef GL_LIGHT7
    case GL_LIGHT7:
#endif
#ifdef GL_LIGHTING
    case GL_LIGHTING:
#endif
#ifdef GL_LIGHT_MODEL_COLOR_CONTROL
    case GL_LIGHT_MODEL_COLOR_CONTROL:
#endif
#ifdef GL_LIGHT_MODEL_LOCAL_VIEWER
    case GL_LIGHT_MODEL_LOCAL_VIEWER:
#endif
#ifdef GL_LIGHT_MODEL_TWO_SIDE
    case GL_LIGHT_MODEL_TWO_SIDE:
#endif
#ifdef GL_LINE_SMOOTH
    case GL_LINE_SMOOTH:
#endif
#ifdef GL_LINE_SMOOTH_HINT
    case GL_LINE_SMOOTH_HINT:
#endif
#ifdef GL_LINE_STIPPLE
    case GL_LINE_STIPPLE:
#endif
#ifdef GL_LINE_STIPPLE_PATTERN
    case GL_LINE_STIPPLE_PATTERN:
#endif
#ifdef GL_LINE_STIPPLE_REPEAT
    case GL_LINE_STIPPLE_REPEAT:
#endif
#ifdef GL_LINE_WIDTH
    case GL_LINE_WIDTH:
#endif
#ifdef GL_LINE_WIDTH_GRANULARITY
    case GL_LINE_WIDTH_GRANULARITY:
#endif
#ifdef GL_LIST_BASE
    case GL_LIST_BASE:
#endif
#ifdef GL_LIST_INDEX
    case GL_LIST_INDEX:
#endif
#ifdef GL_LIST_MODE
    case GL_LIST_MODE:
#endif
#ifdef GL_LOGIC_OP_MODE
    case GL_LOGIC_OP_MODE:
#endif
#ifdef GL_MAP1_COLOR_4
    case GL_MAP1_COLOR_4:
#endif
#ifdef GL_MAP1_GRID_SEGMENTS
    case GL_MAP1_GRID_SEGMENTS:
#endif
#ifdef GL_MAP1_INDEX
    case GL_MAP1_INDEX:
#endif
#ifdef GL_MAP1_NORMAL
    case GL_MAP1_NORMAL:
#endif
#ifdef GL_MAP1_TEXTURE_COORD_1
    case GL_MAP1_TEXTURE_COORD_1:
#endif
#ifdef GL_MAP1_TEXTURE_COORD_2
    case GL_MAP1_TEXTURE_COORD_2:
#endif
#ifdef GL_MAP1_TEXTURE_COORD_3
    case GL_MAP1_TEXTURE_COORD_3:
#endif
#ifdef GL_MAP1_TEXTURE_COORD_4
    case GL_MAP1_TEXTURE_COORD_4:
#endif
#ifdef GL_MAP1_VERTEX_3
    case GL_MAP1_VERTEX_3:
#endif
#ifdef GL_MAP1_VERTEX_4
    case GL_MAP1_VERTEX_4:
#endif
#ifdef GL_MAP2_COLOR_4
    case GL_MAP2_COLOR_4:
#endif
#ifdef GL_MAP2_INDEX
    case GL_MAP2_INDEX:
#endif
#ifdef GL_MAP2_NORMAL
    case GL_MAP2_NORMAL:
#endif
#ifdef GL_MAP2_TEXTURE_COORD_1
    case GL_MAP2_TEXTURE_COORD_1:
#endif
#ifdef GL_MAP2_TEXTURE_COORD_2
    case GL_MAP2_TEXTURE_COORD_2:
#endif
#ifdef GL_MAP2_TEXTURE_COORD_3
    case GL_MAP2_TEXTURE_COORD_3:
#endif
#ifdef GL_MAP2_TEXTURE_COORD_4
    case GL_MAP2_TEXTURE_COORD_4:
#endif
#ifdef GL_MAP2_VERTEX_3
    case GL_MAP2_VERTEX_3:
#endif
#ifdef GL_MAP2_VERTEX_4
    case GL_MAP2_VERTEX_4:
#endif
#ifdef GL_MAP_COLOR
    case GL_MAP_COLOR:
#endif
#ifdef GL_MAP_STENCIL
    case GL_MAP_STENCIL:
#endif
#ifdef GL_MATRIX_MODE
    case GL_MATRIX_MODE:
#endif
#ifdef GL_MAX_3D_TEXTURE_SIZE
    case GL_MAX_3D_TEXTURE_SIZE:
#endif
#ifdef GL_MAX_ATTRIB_STACK_DEPTH
    case GL_MAX_ATTRIB_STACK_DEPTH:
#endif
#ifdef GL_MAX_CLIENT_ATTRIB_STACK_DEPTH
    case GL_MAX_CLIENT_ATTRIB_STACK_DEPTH:
#endif
#ifdef GL_MAX_CLIP_PLANES
    case GL_MAX_CLIP_PLANES:
#endif
#ifdef GL_MAX_COLOR_MATRIX_STACK_DEPTH
    case GL_MAX_COLOR_MATRIX_STACK_DEPTH:
#endif
#ifdef GL_MAX_ELEMENTS_INDICES
    case GL_MAX_ELEMENTS_INDICES:
#endif
#ifdef GL_MAX_ELEMENTS_VERTICES
    case GL_MAX_ELEMENTS_VERTICES:
#endif
#ifdef GL_MAX_EVAL_ORDER
    case GL_MAX_EVAL_ORDER:
#endif
#ifdef GL_MAX_LIGHTS
    case GL_MAX_LIGHTS:
#endif
#ifdef GL_MAX_LIST_NESTING
    case GL_MAX_LIST_NESTING:
#endif
#ifdef GL_MAX_MODELVIEW_STACK_DEPTH
    case GL_MAX_MODELVIEW_STACK_DEPTH:
#endif
#ifdef GL_MAX_NAME_STACK_DEPTH
    case GL_MAX_NAME_STACK_DEPTH:
#endif
#ifdef GL_MAX_PIXEL_MAP_TABLE
    case GL_MAX_PIXEL_MAP_TABLE:
#endif
#ifdef GL_MAX_PROJECTION_STACK_DEPTH
    case GL_MAX_PROJECTION_STACK_DEPTH:
#endif
#ifdef GL_MAX_TEXTURE_SIZE
    case GL_MAX_TEXTURE_SIZE:
#endif
#ifdef GL_MAX_TEXTURE_STACK_DEPTH
    case GL_MAX_TEXTURE_STACK_DEPTH:
#endif
#ifdef GL_MAX_TEXTURE_UNITS_ARB
    case GL_MAX_TEXTURE_UNITS_ARB:
#endif
#ifdef GL_MINMAX
    case GL_MINMAX:
#endif
#ifdef GL_MODELVIEW_STACK_DEPTH
    case GL_MODELVIEW_STACK_DEPTH:
#endif
#ifdef GL_NAME_STACK_DEPTH
    case GL_NAME_STACK_DEPTH:
#endif
#ifdef GL_NORMAL_ARRAY
    case GL_NORMAL_ARRAY:
#endif
#ifdef GL_NORMAL_ARRAY_STRIDE
    case GL_NORMAL_ARRAY_STRIDE:
#endif
#ifdef GL_NORMAL_ARRAY_TYPE
    case GL_NORMAL_ARRAY_TYPE:
#endif
#ifdef GL_NORMALIZE
    case GL_NORMALIZE:
#endif
#ifdef GL_PACK_ALIGNMENT
    case GL_PACK_ALIGNMENT:
#endif
#ifdef GL_PACK_IMAGE_HEIGHT
    case GL_PACK_IMAGE_HEIGHT:
#endif
#ifdef GL_PACK_LSB_FIRST
    case GL_PACK_LSB_FIRST:
#endif
#ifdef GL_PACK_ROW_LENGTH
    case GL_PACK_ROW_LENGTH:
#endif
#ifdef GL_PACK_SKIP_IMAGES
    case GL_PACK_SKIP_IMAGES:
#endif
#ifdef GL_PACK_SKIP_PIXELS
    case GL_PACK_SKIP_PIXELS:
#endif
#ifdef GL_PACK_SKIP_ROWS
    case GL_PACK_SKIP_ROWS:
#endif
#ifdef GL_PACK_SWAP_BYTES
    case GL_PACK_SWAP_BYTES:
#endif
#ifdef GL_PERSPECTIVE_CORRECTION_HINT
    case GL_PERSPECTIVE_CORRECTION_HINT:
#endif
#ifdef GL_PIXEL_MAP_A_TO_A_SIZE
    case GL_PIXEL_MAP_A_TO_A_SIZE:
#endif
#ifdef GL_PIXEL_MAP_B_TO_B_SIZE
    case GL_PIXEL_MAP_B_TO_B_SIZE:
#endif
#ifdef GL_PIXEL_MAP_G_TO_G_SIZE
    case GL_PIXEL_MAP_G_TO_G_SIZE:
#endif
#ifdef GL_PIXEL_MAP_I_TO_A_SIZE
    case GL_PIXEL_MAP_I_TO_A_SIZE:
#endif
#ifdef GL_PIXEL_MAP_I_TO_B_SIZE
    case GL_PIXEL_MAP_I_TO_B_SIZE:
#endif
#ifdef GL_PIXEL_MAP_I_TO_G_SIZE
    case GL_PIXEL_MAP_I_TO_G_SIZE:
#endif
#ifdef GL_PIXEL_MAP_I_TO_I_SIZE
    case GL_PIXEL_MAP_I_TO_I_SIZE:
#endif
#ifdef GL_PIXEL_MAP_I_TO_R_SIZE
    case GL_PIXEL_MAP_I_TO_R_SIZE:
#endif
#ifdef GL_PIXEL_MAP_R_TO_R_SIZE
    case GL_PIXEL_MAP_R_TO_R_SIZE:
#endif
#ifdef GL_PIXEL_MAP_S_TO_S_SIZE
    case GL_PIXEL_MAP_S_TO_S_SIZE:
#endif
#ifdef GL_POINT_SIZE
    case GL_POINT_SIZE:
#endif
#ifdef GL_POINT_SIZE_GRANULARITY
    case GL_POINT_SIZE_GRANULARITY:
#endif
#ifdef GL_POINT_SMOOTH
    case GL_POINT_SMOOTH:
#endif
#ifdef GL_POINT_SMOOTH_HINT
    case GL_POINT_SMOOTH_HINT:
#endif
#ifdef GL_POLYGON_OFFSET_FACTOR
    case GL_POLYGON_OFFSET_FACTOR:
#endif
#ifdef GL_POLYGON_OFFSET_FILL
    case GL_POLYGON_OFFSET_FILL:
#endif
#ifdef GL_POLYGON_OFFSET_LINE
    case GL_POLYGON_OFFSET_LINE:
#endif
#ifdef GL_POLYGON_OFFSET_POINT
    case GL_POLYGON_OFFSET_POINT:
#endif
#ifdef GL_POLYGON_OFFSET_UNITS
    case GL_POLYGON_OFFSET_UNITS:
#endif
#ifdef GL_POLYGON_SMOOTH
    case GL_POLYGON_SMOOTH:
#endif
#ifdef GL_POLYGON_SMOOTH_HINT
    case GL_POLYGON_SMOOTH_HINT:
#endif
#ifdef GL_POLYGON_STIPPLE
    case GL_POLYGON_STIPPLE:
#endif
#ifdef GL_POST_COLOR_MATRIX_ALPHA_BIAS
    case GL_POST_COLOR_MATRIX_ALPHA_BIAS:
#endif
#ifdef GL_POST_COLOR_MATRIX_ALPHA_SCALE
    case GL_POST_COLOR_MATRIX_ALPHA_SCALE:
#endif
#ifdef GL_POST_COLOR_MATRIX_BLUE_BIAS
    case GL_POST_COLOR_MATRIX_BLUE_BIAS:
#endif
#ifdef GL_POST_COLOR_MATRIX_BLUE_SCALE
    case GL_POST_COLOR_MATRIX_BLUE_SCALE:
#endif
#ifdef GL_POST_COLOR_MATRIX_COLOR_TABLE
    case GL_POST_COLOR_MATRIX_COLOR_TABLE:
#endif
#ifdef GL_POST_COLOR_MATRIX_GREEN_BIAS
    case GL_POST_COLOR_MATRIX_GREEN_BIAS:
#endif
#ifdef GL_POST_COLOR_MATRIX_GREEN_SCALE
    case GL_POST_COLOR_MATRIX_GREEN_SCALE:
#endif
#ifdef GL_POST_COLOR_MATRIX_RED_BIAS
    case GL_POST_COLOR_MATRIX_RED_BIAS:
#endif
#ifdef GL_POST_COLOR_MATRIX_RED_SCALE
    case GL_POST_COLOR_MATRIX_RED_SCALE:
#endif
#ifdef GL_POST_CONVOLUTION_ALPHA_BIAS
    case GL_POST_CONVOLUTION_ALPHA_BIAS:
#endif
#ifdef GL_POST_CONVOLUTION_ALPHA_SCALE
    case GL_POST_CONVOLUTION_ALPHA_SCALE:
#endif
#ifdef GL_POST_CONVOLUTION_BLUE_BIAS
    case GL_POST_CONVOLUTION_BLUE_BIAS:
#endif
#ifdef GL_POST_CONVOLUTION_BLUE_SCALE
    case GL_POST_CONVOLUTION_BLUE_SCALE:
#endif
#ifdef GL_POST_CONVOLUTION_COLOR_TABLE
    case GL_POST_CONVOLUTION_COLOR_TABLE:
#endif
#ifdef GL_POST_CONVOLUTION_GREEN_BIAS
    case GL_POST_CONVOLUTION_GREEN_BIAS:
#endif
#ifdef GL_POST_CONVOLUTION_GREEN_SCALE
    case GL_POST_CONVOLUTION_GREEN_SCALE:
#endif
#ifdef GL_POST_CONVOLUTION_RED_BIAS
    case GL_POST_CONVOLUTION_RED_BIAS:
#endif
#ifdef GL_POST_CONVOLUTION_RED_SCALE
    case GL_POST_CONVOLUTION_RED_SCALE:
#endif
#ifdef GL_PROJECTION_STACK_DEPTH
    case GL_PROJECTION_STACK_DEPTH:
#endif
#ifdef GL_READ_BUFFER
    case GL_READ_BUFFER:
#endif
#ifdef GL_RED_BIAS
    case GL_RED_BIAS:
#endif
#ifdef GL_RED_BITS
    case GL_RED_BITS:
#endif
#ifdef GL_RED_SCALE
    case GL_RED_SCALE:
#endif
#ifdef GL_RENDER_MODE
    case GL_RENDER_MODE:
#endif
#ifdef GL_RESCALE_NORMAL
    case GL_RESCALE_NORMAL:
#endif
#ifdef GL_RGBA_MODE
    case GL_RGBA_MODE:
#endif
#ifdef GL_SCISSOR_TEST
    case GL_SCISSOR_TEST:
#endif
#ifdef GL_SELECTION_BUFFER_SIZE
    case GL_SELECTION_BUFFER_SIZE:
#endif
#ifdef GL_SEPARABLE_2D
    case GL_SEPARABLE_2D:
#endif
#ifdef GL_SHADE_MODEL
    case GL_SHADE_MODEL:
#endif
#ifdef GL_STENCIL_BITS
    case GL_STENCIL_BITS:
#endif
#ifdef GL_STENCIL_CLEAR_VALUE
    case GL_STENCIL_CLEAR_VALUE:
#endif
#ifdef GL_STENCIL_FAIL
    case GL_STENCIL_FAIL:
#endif
#ifdef GL_STENCIL_FUNC
    case GL_STENCIL_FUNC:
#endif
#ifdef GL_STENCIL_PASS_DEPTH_FAIL
    case GL_STENCIL_PASS_DEPTH_FAIL:
#endif
#ifdef GL_STENCIL_PASS_DEPTH_PASS
    case GL_STENCIL_PASS_DEPTH_PASS:
#endif
#ifdef GL_STENCIL_REF
    case GL_STENCIL_REF:
#endif
#ifdef GL_STENCIL_TEST
    case GL_STENCIL_TEST:
#endif
#ifdef GL_STENCIL_VALUE_MASK
    case GL_STENCIL_VALUE_MASK:
#endif
#ifdef GL_STENCIL_WRITEMASK
    case GL_STENCIL_WRITEMASK:
#endif
#ifdef GL_STEREO
    case GL_STEREO:
#endif
#ifdef GL_SUBPIXEL_BITS
    case GL_SUBPIXEL_BITS:
#endif
#ifdef GL_TEXTURE_1D
    case GL_TEXTURE_1D:
#endif
#ifdef GL_TEXTURE_2D
    case GL_TEXTURE_2D:
#endif
#ifdef GL_TEXTURE_3D
    case GL_TEXTURE_3D:
#endif
#ifdef GL_TEXTURE_BINDING_1D
    case GL_TEXTURE_BINDING_1D:
#endif
#ifdef GL_TEXTURE_BINDING_2D
    case GL_TEXTURE_BINDING_2D:
#endif
#ifdef GL_TEXTURE_BINDING_3D
    case GL_TEXTURE_BINDING_3D:
#endif
#ifdef GL_TEXTURE_COORD_ARRAY
    case GL_TEXTURE_COORD_ARRAY:
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_SIZE
    case GL_TEXTURE_COORD_ARRAY_SIZE:
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_STRIDE
    case GL_TEXTURE_COORD_ARRAY_STRIDE:
#endif
#ifdef GL_TEXTURE_COORD_ARRAY_TYPE
    case GL_TEXTURE_COORD_ARRAY_TYPE:
#endif
#ifdef GL_TEXTURE_GEN_Q
    case GL_TEXTURE_GEN_Q:
#endif
#ifdef GL_TEXTURE_GEN_R
    case GL_TEXTURE_GEN_R:
#endif
#ifdef GL_TEXTURE_GEN_S
    case GL_TEXTURE_GEN_S:
#endif
#ifdef GL_TEXTURE_GEN_T
    case GL_TEXTURE_GEN_T:
#endif
#ifdef GL_TEXTURE_STACK_DEPTH
    case GL_TEXTURE_STACK_DEPTH:
#endif
#ifdef GL_UNPACK_ALIGNMENT
    case GL_UNPACK_ALIGNMENT:
#endif
#ifdef GL_UNPACK_IMAGE_HEIGHT
    case GL_UNPACK_IMAGE_HEIGHT:
#endif
#ifdef GL_UNPACK_LSB_FIRST
    case GL_UNPACK_LSB_FIRST:
#endif
#ifdef GL_UNPACK_ROW_LENGTH
    case GL_UNPACK_ROW_LENGTH:
#endif
#ifdef GL_UNPACK_SKIP_IMAGES
    case GL_UNPACK_SKIP_IMAGES:
#endif
#ifdef GL_UNPACK_SKIP_PIXELS
    case GL_UNPACK_SKIP_PIXELS:
#endif
#ifdef GL_UNPACK_SKIP_ROWS
    case GL_UNPACK_SKIP_ROWS:
#endif
#ifdef GL_UNPACK_SWAP_BYTES
    case GL_UNPACK_SWAP_BYTES:
#endif
#ifdef GL_VERTEX_ARRAY
    case GL_VERTEX_ARRAY:
#endif
#ifdef GL_VERTEX_ARRAY_SIZE
    case GL_VERTEX_ARRAY_SIZE:
#endif
#ifdef GL_VERTEX_ARRAY_STRIDE
    case GL_VERTEX_ARRAY_STRIDE:
#endif
#ifdef GL_VERTEX_ARRAY_TYPE
    case GL_VERTEX_ARRAY_TYPE:
#endif
#ifdef GL_ZOOM_X
    case GL_ZOOM_X:
#endif
#ifdef GL_ZOOM_Y
    case GL_ZOOM_Y:
#endif
      return 1;
#ifdef GL_ALIASED_LINE_WIDTH_RANGE
    case GL_ALIASED_LINE_WIDTH_RANGE:
#endif
#ifdef GL_ALIASED_POINT_SIZE_RANGE
    case GL_ALIASED_POINT_SIZE_RANGE:
#endif
#ifdef GL_DEPTH_RANGE
    case GL_DEPTH_RANGE:
#endif
#ifdef GL_LINE_WIDTH_RANGE
    case GL_LINE_WIDTH_RANGE:
#endif
#ifdef GL_MAP1_GRID_DOMAIN
    case GL_MAP1_GRID_DOMAIN:
#endif
#ifdef GL_MAP2_GRID_SEGMENTS
    case GL_MAP2_GRID_SEGMENTS:
#endif
#ifdef GL_MAX_VIEWPORT_DIMS
    case GL_MAX_VIEWPORT_DIMS:
#endif
#ifdef GL_POINT_SIZE_RANGE
    case GL_POINT_SIZE_RANGE:
#endif
#ifdef GL_POLYGON_MODE
    case GL_POLYGON_MODE:
#endif
      return 2;
#ifdef GL_CURRENT_NORMAL
    case GL_CURRENT_NORMAL:
#endif
      return 3;
#ifdef GL_ACCUM_CLEAR_VALUE
    case GL_ACCUM_CLEAR_VALUE:
#endif
#ifdef GL_BLEND_COLOR
    case GL_BLEND_COLOR:
#endif
#ifdef GL_COLOR_CLEAR_VALUE
    case GL_COLOR_CLEAR_VALUE:
#endif
#ifdef GL_COLOR_WRITEMASK
    case GL_COLOR_WRITEMASK:
#endif
#ifdef GL_CURRENT_COLOR
    case GL_CURRENT_COLOR:
#endif
#ifdef GL_CURRENT_RASTER_COLOR
    case GL_CURRENT_RASTER_COLOR:
#endif
#ifdef GL_CURRENT_RASTER_POSITION
    case GL_CURRENT_RASTER_POSITION:
#endif
#ifdef GL_CURRENT_RASTER_TEXTURE_COORDS
    case GL_CURRENT_RASTER_TEXTURE_COORDS:
#endif
#ifdef GL_CURRENT_TEXTURE_COORDS
    case GL_CURRENT_TEXTURE_COORDS:
#endif
#ifdef GL_FOG_COLOR
    case GL_FOG_COLOR:
#endif
#ifdef GL_LIGHT_MODEL_AMBIENT
    case GL_LIGHT_MODEL_AMBIENT:
#endif
#ifdef GL_MAP2_GRID_DOMAIN
    case GL_MAP2_GRID_DOMAIN:
#endif
#ifdef GL_SCISSOR_BOX
    case GL_SCISSOR_BOX:
#endif
#ifdef GL_VIEWPORT
    case GL_VIEWPORT:
#endif
      return 4;
#ifdef GL_COLOR_MATRIX
    case GL_COLOR_MATRIX:
#endif
#ifdef GL_MODELVIEW_MATRIX
    case GL_MODELVIEW_MATRIX:
#endif
#ifdef GL_PROJECTION_MATRIX
    case GL_PROJECTION_MATRIX:
#endif
#ifdef GL_TEXTURE_MATRIX
    case GL_TEXTURE_MATRIX:
#endif
      return 16;
    default:
      return -1;
    }
}
