#!/usr/bin/perl
# this script takes c function declarations and modifies them
# to have each function declaration on one line
# example:
#
# void func(int x,
#           int y);
#
# gets:
#
# void func(int x,int y);
#
#
# for now this is not a general purpose script - it is intented to work with GL/gl.h
#
while (<STDIN>) {
  if (/^GLAPI.*/) {
    chomp;
    print $_;
    if (not /.*\)./) {
      do {
	die unless $_=<STDIN>;
	chomp;
	print $_;
      }while (not /.*\).*/);
    }
    print "\n";
  }elsif (/^\/\* ([0-9])\.([0-9]) functions \*\//) {
    print $_;
  }
}
