/* DO NOT EDIT THIS FILE - it is generated by jsgl_gen */
{"ClearIndex",js_glClearIndex,1,0,0},
{"ClearColor",js_glClearColor,4,0,0},
{"Clear",js_glClear,1,0,0},
{"IndexMask",js_glIndexMask,1,0,0},
{"ColorMask",js_glColorMask,4,0,0},
{"AlphaFunc",js_glAlphaFunc,2,0,0},
{"BlendFunc",js_glBlendFunc,2,0,0},
{"LogicOp",js_glLogicOp,1,0,0},
{"CullFace",js_glCullFace,1,0,0},
{"FrontFace",js_glFrontFace,1,0,0},
{"PointSize",js_glPointSize,1,0,0},
{"LineWidth",js_glLineWidth,1,0,0},
{"LineStipple",js_glLineStipple,2,0,0},
{"PolygonMode",js_glPolygonMode,2,0,0},
{"PolygonOffset",js_glPolygonOffset,2,0,0},
/* TODO: glPolygonStipple */
/* TODO: glGetPolygonStipple */
{"EdgeFlag",js_glEdgeFlag,1,0,0},
/* TODO: glEdgeFlagv */
{"Scissor",js_glScissor,4,0,0},
/* TODO: glClipPlane */
/* TODO: glGetClipPlane */
{"DrawBuffer",js_glDrawBuffer,1,0,0},
{"ReadBuffer",js_glReadBuffer,1,0,0},
{"Enable",js_glEnable,1,0,0},
{"Disable",js_glDisable,1,0,0},
{"IsEnabled",js_glIsEnabled,1,0,0},
{"EnableClientState",js_glEnableClientState,1,0,0},
{"DisableClientState",js_glDisableClientState,1,0,0},
/* TODO: glGetBooleanv */
/* TODO: glGetDoublev */
/* TODO: glGetFloatv */
/* TODO: glGetIntegerv */
{"PushAttrib",js_glPushAttrib,1,0,0},
{"PopAttrib",js_glPopAttrib,0,0,0},
{"PushClientAttrib",js_glPushClientAttrib,1,0,0},
{"PopClientAttrib",js_glPopClientAttrib,0,0,0},
{"RenderMode",js_glRenderMode,1,0,0},
{"GetError",js_glGetError,0,0,0},
{"GetString",js_glGetString,1,0,0},
{"Finish",js_glFinish,0,0,0},
{"Flush",js_glFlush,0,0,0},
{"Hint",js_glHint,2,0,0},
{"ClearDepth",js_glClearDepth,1,0,0},
{"DepthFunc",js_glDepthFunc,1,0,0},
{"DepthMask",js_glDepthMask,1,0,0},
{"DepthRange",js_glDepthRange,2,0,0},
{"ClearAccum",js_glClearAccum,4,0,0},
{"Accum",js_glAccum,2,0,0},
{"MatrixMode",js_glMatrixMode,1,0,0},
{"Ortho",js_glOrtho,6,0,0},
{"Frustum",js_glFrustum,6,0,0},
{"Viewport",js_glViewport,4,0,0},
{"PushMatrix",js_glPushMatrix,0,0,0},
{"PopMatrix",js_glPopMatrix,0,0,0},
{"LoadIdentity",js_glLoadIdentity,0,0,0},
{"LoadMatrixd",js_glLoadMatrixd,1,0,0},
{"LoadMatrixf",js_glLoadMatrixf,1,0,0},
{"MultMatrixd",js_glMultMatrixd,1,0,0},
{"MultMatrixf",js_glMultMatrixf,1,0,0},
{"Rotated",js_glRotated,4,0,0},
{"Rotatef",js_glRotatef,4,0,0},
{"Scaled",js_glScaled,3,0,0},
{"Scalef",js_glScalef,3,0,0},
{"Translated",js_glTranslated,3,0,0},
{"Translatef",js_glTranslatef,3,0,0},
{"IsList",js_glIsList,1,0,0},
{"DeleteLists",js_glDeleteLists,2,0,0},
{"GenLists",js_glGenLists,1,0,0},
{"NewList",js_glNewList,2,0,0},
{"EndList",js_glEndList,0,0,0},
{"CallList",js_glCallList,1,0,0},
/* TODO: glCallLists */
{"ListBase",js_glListBase,1,0,0},
{"Begin",js_glBegin,1,0,0},
{"End",js_glEnd,0,0,0},
{"Vertex2d",js_glVertex2d,2,0,0},
{"Vertex2f",js_glVertex2f,2,0,0},
{"Vertex2i",js_glVertex2i,2,0,0},
{"Vertex2s",js_glVertex2s,2,0,0},
{"Vertex3d",js_glVertex3d,3,0,0},
{"Vertex3f",js_glVertex3f,3,0,0},
{"Vertex3i",js_glVertex3i,3,0,0},
{"Vertex3s",js_glVertex3s,3,0,0},
{"Vertex4d",js_glVertex4d,4,0,0},
{"Vertex4f",js_glVertex4f,4,0,0},
{"Vertex4i",js_glVertex4i,4,0,0},
{"Vertex4s",js_glVertex4s,4,0,0},
{"Vertex2dv",js_glVertex2dv,1,0,0},
{"Vertex2fv",js_glVertex2fv,1,0,0},
{"Vertex2iv",js_glVertex2iv,1,0,0},
{"Vertex2sv",js_glVertex2sv,1,0,0},
{"Vertex3dv",js_glVertex3dv,1,0,0},
{"Vertex3fv",js_glVertex3fv,1,0,0},
{"Vertex3iv",js_glVertex3iv,1,0,0},
{"Vertex3sv",js_glVertex3sv,1,0,0},
{"Vertex4dv",js_glVertex4dv,1,0,0},
{"Vertex4fv",js_glVertex4fv,1,0,0},
{"Vertex4iv",js_glVertex4iv,1,0,0},
{"Vertex4sv",js_glVertex4sv,1,0,0},
{"Normal3b",js_glNormal3b,3,0,0},
{"Normal3d",js_glNormal3d,3,0,0},
{"Normal3f",js_glNormal3f,3,0,0},
{"Normal3i",js_glNormal3i,3,0,0},
{"Normal3s",js_glNormal3s,3,0,0},
{"Normal3bv",js_glNormal3bv,1,0,0},
{"Normal3dv",js_glNormal3dv,1,0,0},
{"Normal3fv",js_glNormal3fv,1,0,0},
{"Normal3iv",js_glNormal3iv,1,0,0},
{"Normal3sv",js_glNormal3sv,1,0,0},
{"Indexd",js_glIndexd,1,0,0},
{"Indexf",js_glIndexf,1,0,0},
{"Indexi",js_glIndexi,1,0,0},
{"Indexs",js_glIndexs,1,0,0},
{"Indexub",js_glIndexub,1,0,0},
/* TODO: glIndexdv */
/* TODO: glIndexfv */
/* TODO: glIndexiv */
/* TODO: glIndexsv */
/* TODO: glIndexubv */
{"Color3b",js_glColor3b,3,0,0},
{"Color3d",js_glColor3d,3,0,0},
{"Color3f",js_glColor3f,3,0,0},
{"Color3i",js_glColor3i,3,0,0},
{"Color3s",js_glColor3s,3,0,0},
{"Color3ub",js_glColor3ub,3,0,0},
{"Color3ui",js_glColor3ui,3,0,0},
{"Color3us",js_glColor3us,3,0,0},
{"Color4b",js_glColor4b,4,0,0},
{"Color4d",js_glColor4d,4,0,0},
{"Color4f",js_glColor4f,4,0,0},
{"Color4i",js_glColor4i,4,0,0},
{"Color4s",js_glColor4s,4,0,0},
{"Color4ub",js_glColor4ub,4,0,0},
{"Color4ui",js_glColor4ui,4,0,0},
{"Color4us",js_glColor4us,4,0,0},
{"Color3bv",js_glColor3bv,1,0,0},
{"Color3dv",js_glColor3dv,1,0,0},
{"Color3fv",js_glColor3fv,1,0,0},
{"Color3iv",js_glColor3iv,1,0,0},
{"Color3sv",js_glColor3sv,1,0,0},
{"Color3ubv",js_glColor3ubv,1,0,0},
{"Color3uiv",js_glColor3uiv,1,0,0},
{"Color3usv",js_glColor3usv,1,0,0},
{"Color4bv",js_glColor4bv,1,0,0},
{"Color4dv",js_glColor4dv,1,0,0},
{"Color4fv",js_glColor4fv,1,0,0},
{"Color4iv",js_glColor4iv,1,0,0},
{"Color4sv",js_glColor4sv,1,0,0},
{"Color4ubv",js_glColor4ubv,1,0,0},
{"Color4uiv",js_glColor4uiv,1,0,0},
{"Color4usv",js_glColor4usv,1,0,0},
{"TexCoord1d",js_glTexCoord1d,1,0,0},
{"TexCoord1f",js_glTexCoord1f,1,0,0},
{"TexCoord1i",js_glTexCoord1i,1,0,0},
{"TexCoord1s",js_glTexCoord1s,1,0,0},
{"TexCoord2d",js_glTexCoord2d,2,0,0},
{"TexCoord2f",js_glTexCoord2f,2,0,0},
{"TexCoord2i",js_glTexCoord2i,2,0,0},
{"TexCoord2s",js_glTexCoord2s,2,0,0},
{"TexCoord3d",js_glTexCoord3d,3,0,0},
{"TexCoord3f",js_glTexCoord3f,3,0,0},
{"TexCoord3i",js_glTexCoord3i,3,0,0},
{"TexCoord3s",js_glTexCoord3s,3,0,0},
{"TexCoord4d",js_glTexCoord4d,4,0,0},
{"TexCoord4f",js_glTexCoord4f,4,0,0},
{"TexCoord4i",js_glTexCoord4i,4,0,0},
{"TexCoord4s",js_glTexCoord4s,4,0,0},
{"TexCoord1dv",js_glTexCoord1dv,1,0,0},
{"TexCoord1fv",js_glTexCoord1fv,1,0,0},
{"TexCoord1iv",js_glTexCoord1iv,1,0,0},
{"TexCoord1sv",js_glTexCoord1sv,1,0,0},
{"TexCoord2dv",js_glTexCoord2dv,1,0,0},
{"TexCoord2fv",js_glTexCoord2fv,1,0,0},
{"TexCoord2iv",js_glTexCoord2iv,1,0,0},
{"TexCoord2sv",js_glTexCoord2sv,1,0,0},
{"TexCoord3dv",js_glTexCoord3dv,1,0,0},
{"TexCoord3fv",js_glTexCoord3fv,1,0,0},
{"TexCoord3iv",js_glTexCoord3iv,1,0,0},
{"TexCoord3sv",js_glTexCoord3sv,1,0,0},
{"TexCoord4dv",js_glTexCoord4dv,1,0,0},
{"TexCoord4fv",js_glTexCoord4fv,1,0,0},
{"TexCoord4iv",js_glTexCoord4iv,1,0,0},
{"TexCoord4sv",js_glTexCoord4sv,1,0,0},
{"RasterPos2d",js_glRasterPos2d,2,0,0},
{"RasterPos2f",js_glRasterPos2f,2,0,0},
{"RasterPos2i",js_glRasterPos2i,2,0,0},
{"RasterPos2s",js_glRasterPos2s,2,0,0},
{"RasterPos3d",js_glRasterPos3d,3,0,0},
{"RasterPos3f",js_glRasterPos3f,3,0,0},
{"RasterPos3i",js_glRasterPos3i,3,0,0},
{"RasterPos3s",js_glRasterPos3s,3,0,0},
{"RasterPos4d",js_glRasterPos4d,4,0,0},
{"RasterPos4f",js_glRasterPos4f,4,0,0},
{"RasterPos4i",js_glRasterPos4i,4,0,0},
{"RasterPos4s",js_glRasterPos4s,4,0,0},
{"RasterPos2dv",js_glRasterPos2dv,1,0,0},
{"RasterPos2fv",js_glRasterPos2fv,1,0,0},
{"RasterPos2iv",js_glRasterPos2iv,1,0,0},
{"RasterPos2sv",js_glRasterPos2sv,1,0,0},
{"RasterPos3dv",js_glRasterPos3dv,1,0,0},
{"RasterPos3fv",js_glRasterPos3fv,1,0,0},
{"RasterPos3iv",js_glRasterPos3iv,1,0,0},
{"RasterPos3sv",js_glRasterPos3sv,1,0,0},
{"RasterPos4dv",js_glRasterPos4dv,1,0,0},
{"RasterPos4fv",js_glRasterPos4fv,1,0,0},
{"RasterPos4iv",js_glRasterPos4iv,1,0,0},
{"RasterPos4sv",js_glRasterPos4sv,1,0,0},
{"Rectd",js_glRectd,4,0,0},
{"Rectf",js_glRectf,4,0,0},
{"Recti",js_glRecti,4,0,0},
{"Rects",js_glRects,4,0,0},
/* TODO: glRectdv */
/* TODO: glRectfv */
/* TODO: glRectiv */
/* TODO: glRectsv */
/* TODO: glVertexPointer */
/* TODO: glNormalPointer */
/* TODO: glColorPointer */
/* TODO: glIndexPointer */
/* TODO: glTexCoordPointer */
/* TODO: glEdgeFlagPointer */
/* TODO: glGetPointerv */
{"ArrayElement",js_glArrayElement,1,0,0},
{"DrawArrays",js_glDrawArrays,3,0,0},
/* TODO: glDrawElements */
/* TODO: glInterleavedArrays */
{"ShadeModel",js_glShadeModel,1,0,0},
{"Lightf",js_glLightf,3,0,0},
{"Lighti",js_glLighti,3,0,0},
/* TODO: glLightfv */
/* TODO: glLightiv */
/* TODO: glGetLightfv */
/* TODO: glGetLightiv */
{"LightModelf",js_glLightModelf,2,0,0},
{"LightModeli",js_glLightModeli,2,0,0},
/* TODO: glLightModelfv */
/* TODO: glLightModeliv */
{"Materialf",js_glMaterialf,3,0,0},
{"Materiali",js_glMateriali,3,0,0},
/* TODO: glMaterialfv */
/* TODO: glMaterialiv */
/* TODO: glGetMaterialfv */
/* TODO: glGetMaterialiv */
{"ColorMaterial",js_glColorMaterial,2,0,0},
{"PixelZoom",js_glPixelZoom,2,0,0},
{"PixelStoref",js_glPixelStoref,2,0,0},
{"PixelStorei",js_glPixelStorei,2,0,0},
{"PixelTransferf",js_glPixelTransferf,2,0,0},
{"PixelTransferi",js_glPixelTransferi,2,0,0},
/* TODO: glPixelMapfv */
/* TODO: glPixelMapuiv */
/* TODO: glPixelMapusv */
/* TODO: glGetPixelMapfv */
/* TODO: glGetPixelMapuiv */
/* TODO: glGetPixelMapusv */
/* TODO: glBitmap */
/* TODO: glReadPixels */
/* TODO: glDrawPixels */
{"CopyPixels",js_glCopyPixels,5,0,0},
{"StencilFunc",js_glStencilFunc,3,0,0},
{"StencilMask",js_glStencilMask,1,0,0},
{"StencilOp",js_glStencilOp,3,0,0},
{"ClearStencil",js_glClearStencil,1,0,0},
{"TexGend",js_glTexGend,3,0,0},
{"TexGenf",js_glTexGenf,3,0,0},
{"TexGeni",js_glTexGeni,3,0,0},
/* TODO: glTexGendv */
/* TODO: glTexGenfv */
/* TODO: glTexGeniv */
/* TODO: glGetTexGendv */
/* TODO: glGetTexGenfv */
/* TODO: glGetTexGeniv */
{"TexEnvf",js_glTexEnvf,3,0,0},
{"TexEnvi",js_glTexEnvi,3,0,0},
/* TODO: glTexEnvfv */
/* TODO: glTexEnviv */
/* TODO: glGetTexEnvfv */
/* TODO: glGetTexEnviv */
{"TexParameterf",js_glTexParameterf,3,0,0},
{"TexParameteri",js_glTexParameteri,3,0,0},
/* TODO: glTexParameterfv */
/* TODO: glTexParameteriv */
/* TODO: glGetTexParameterfv */
/* TODO: glGetTexParameteriv */
/* TODO: glGetTexLevelParameterfv */
/* TODO: glGetTexLevelParameteriv */
/* TODO: glTexImage1D */
/* TODO: glTexImage2D */
/* TODO: glGetTexImage */
#ifdef GL_VERSION_1_1
/* TODO: glGenTextures */
/* TODO: glDeleteTextures */
{"BindTexture",js_glBindTexture,2,0,0},
/* TODO: glPrioritizeTextures */
/* TODO: glAreTexturesResident */
{"IsTexture",js_glIsTexture,1,0,0},
/* TODO: glTexSubImage1D */
/* TODO: glTexSubImage2D */
{"CopyTexImage1D",js_glCopyTexImage1D,7,0,0},
{"CopyTexImage2D",js_glCopyTexImage2D,8,0,0},
{"CopyTexSubImage1D",js_glCopyTexSubImage1D,6,0,0},
{"CopyTexSubImage2D",js_glCopyTexSubImage2D,8,0,0},
/* TODO: glMap1d */
/* TODO: glMap1f */
/* TODO: glMap2d */
/* TODO: glMap2f */
/* TODO: glGetMapdv */
/* TODO: glGetMapfv */
/* TODO: glGetMapiv */
{"EvalCoord1d",js_glEvalCoord1d,1,0,0},
{"EvalCoord1f",js_glEvalCoord1f,1,0,0},
{"EvalCoord1dv",js_glEvalCoord1dv,1,0,0},
{"EvalCoord1fv",js_glEvalCoord1fv,1,0,0},
{"EvalCoord2d",js_glEvalCoord2d,2,0,0},
{"EvalCoord2f",js_glEvalCoord2f,2,0,0},
{"EvalCoord2dv",js_glEvalCoord2dv,1,0,0},
{"EvalCoord2fv",js_glEvalCoord2fv,1,0,0},
{"MapGrid1d",js_glMapGrid1d,3,0,0},
{"MapGrid1f",js_glMapGrid1f,3,0,0},
{"MapGrid2d",js_glMapGrid2d,6,0,0},
{"MapGrid2f",js_glMapGrid2f,6,0,0},
{"EvalPoint1",js_glEvalPoint1,1,0,0},
{"EvalPoint2",js_glEvalPoint2,2,0,0},
{"EvalMesh1",js_glEvalMesh1,3,0,0},
{"EvalMesh2",js_glEvalMesh2,5,0,0},
{"Fogf",js_glFogf,2,0,0},
{"Fogi",js_glFogi,2,0,0},
/* TODO: glFogfv */
/* TODO: glFogiv */
/* TODO: glFeedbackBuffer */
{"PassThrough",js_glPassThrough,1,0,0},
/* TODO: glSelectBuffer */
{"InitNames",js_glInitNames,0,0,0},
{"LoadName",js_glLoadName,1,0,0},
{"PushName",js_glPushName,1,0,0},
{"PopName",js_glPopName,0,0,0},
#endif
#ifdef GL_VERSION_1_2
/* TODO: glDrawRangeElements */
/* TODO: glTexImage3D */
/* TODO: glTexSubImage3D */
{"CopyTexSubImage3D",js_glCopyTexSubImage3D,9,0,0},
/* TODO: glColorTable */
/* TODO: glColorSubTable */
/* TODO: glColorTableParameteriv */
/* TODO: glColorTableParameterfv */
{"CopyColorSubTable",js_glCopyColorSubTable,5,0,0},
{"CopyColorTable",js_glCopyColorTable,5,0,0},
/* TODO: glGetColorTable */
/* TODO: glGetColorTableParameterfv */
/* TODO: glGetColorTableParameteriv */
{"BlendEquation",js_glBlendEquation,1,0,0},
{"BlendColor",js_glBlendColor,4,0,0},
{"Histogram",js_glHistogram,4,0,0},
{"ResetHistogram",js_glResetHistogram,1,0,0},
/* TODO: glGetHistogram */
/* TODO: glGetHistogramParameterfv */
/* TODO: glGetHistogramParameteriv */
{"Minmax",js_glMinmax,3,0,0},
{"ResetMinmax",js_glResetMinmax,1,0,0},
/* TODO: glGetMinmax */
/* TODO: glGetMinmaxParameterfv */
/* TODO: glGetMinmaxParameteriv */
/* TODO: glConvolutionFilter1D */
/* TODO: glConvolutionFilter2D */
{"ConvolutionParameterf",js_glConvolutionParameterf,3,0,0},
/* TODO: glConvolutionParameterfv */
{"ConvolutionParameteri",js_glConvolutionParameteri,3,0,0},
/* TODO: glConvolutionParameteriv */
{"CopyConvolutionFilter1D",js_glCopyConvolutionFilter1D,5,0,0},
{"CopyConvolutionFilter2D",js_glCopyConvolutionFilter2D,6,0,0},
/* TODO: glGetConvolutionFilter */
/* TODO: glGetConvolutionParameterfv */
/* TODO: glGetConvolutionParameteriv */
/* TODO: glSeparableFilter2D */
/* TODO: glGetSeparableFilter */
#endif
#ifdef GL_VERSION_1_3
{"ActiveTexture",js_glActiveTexture,1,0,0},
{"ClientActiveTexture",js_glClientActiveTexture,1,0,0},
/* TODO: glCompressedTexImage1D */
/* TODO: glCompressedTexImage2D */
/* TODO: glCompressedTexImage3D */
/* TODO: glCompressedTexSubImage1D */
/* TODO: glCompressedTexSubImage2D */
/* TODO: glCompressedTexSubImage3D */
/* TODO: glGetCompressedTexImage */
{"MultiTexCoord1d",js_glMultiTexCoord1d,2,0,0},
{"MultiTexCoord1dv",js_glMultiTexCoord1dv,2,0,0},
{"MultiTexCoord1f",js_glMultiTexCoord1f,2,0,0},
{"MultiTexCoord1fv",js_glMultiTexCoord1fv,2,0,0},
{"MultiTexCoord1i",js_glMultiTexCoord1i,2,0,0},
{"MultiTexCoord1iv",js_glMultiTexCoord1iv,2,0,0},
{"MultiTexCoord1s",js_glMultiTexCoord1s,2,0,0},
{"MultiTexCoord1sv",js_glMultiTexCoord1sv,2,0,0},
{"MultiTexCoord2d",js_glMultiTexCoord2d,3,0,0},
{"MultiTexCoord2dv",js_glMultiTexCoord2dv,2,0,0},
{"MultiTexCoord2f",js_glMultiTexCoord2f,3,0,0},
{"MultiTexCoord2fv",js_glMultiTexCoord2fv,2,0,0},
{"MultiTexCoord2i",js_glMultiTexCoord2i,3,0,0},
{"MultiTexCoord2iv",js_glMultiTexCoord2iv,2,0,0},
{"MultiTexCoord2s",js_glMultiTexCoord2s,3,0,0},
{"MultiTexCoord2sv",js_glMultiTexCoord2sv,2,0,0},
{"MultiTexCoord3d",js_glMultiTexCoord3d,4,0,0},
{"MultiTexCoord3dv",js_glMultiTexCoord3dv,2,0,0},
{"MultiTexCoord3f",js_glMultiTexCoord3f,4,0,0},
{"MultiTexCoord3fv",js_glMultiTexCoord3fv,2,0,0},
{"MultiTexCoord3i",js_glMultiTexCoord3i,4,0,0},
{"MultiTexCoord3iv",js_glMultiTexCoord3iv,2,0,0},
{"MultiTexCoord3s",js_glMultiTexCoord3s,4,0,0},
{"MultiTexCoord3sv",js_glMultiTexCoord3sv,2,0,0},
{"MultiTexCoord4d",js_glMultiTexCoord4d,5,0,0},
{"MultiTexCoord4dv",js_glMultiTexCoord4dv,2,0,0},
{"MultiTexCoord4f",js_glMultiTexCoord4f,5,0,0},
{"MultiTexCoord4fv",js_glMultiTexCoord4fv,2,0,0},
{"MultiTexCoord4i",js_glMultiTexCoord4i,5,0,0},
{"MultiTexCoord4iv",js_glMultiTexCoord4iv,2,0,0},
{"MultiTexCoord4s",js_glMultiTexCoord4s,5,0,0},
{"MultiTexCoord4sv",js_glMultiTexCoord4sv,2,0,0},
{"LoadTransposeMatrixd",js_glLoadTransposeMatrixd,1,0,0},
{"LoadTransposeMatrixf",js_glLoadTransposeMatrixf,1,0,0},
{"MultTransposeMatrixd",js_glMultTransposeMatrixd,1,0,0},
{"MultTransposeMatrixf",js_glMultTransposeMatrixf,1,0,0},
{"SampleCoverage",js_glSampleCoverage,2,0,0},
#endif
