#!/bin/bash

# convert binary file to base64 encoded javascript
# string/resource for egachine

#CC=${CC:=cc}
#$CC -o bin2hex bin2hex.c && ./bin2hex ball|smjs
mimencode|(
    if [ "x$1" != "x" ]; then
	echo "EGachine.addResource('$1',"
    fi
    read a
    echo \'$a\\
    while read a; do 
	echo $a\\
    done
    echo -n \'
    if [ "x$1" != "x" ]; then
	echo ");"
    fi
)
